services:
  forumline:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.go-forumline
    ports:
      - "3001:3000"
    env_file:
      - services/forumline-web/.env.local
    environment:
      - PORT=3000
