// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: call.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptCall = `-- name: AcceptCall :exec
UPDATE forumline_calls SET status = 'active', started_at = now() WHERE id = $1
`

func (q *Queries) AcceptCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptCall, id)
	return err
}

const cleanupStaleCalls = `-- name: CleanupStaleCalls :execrows
UPDATE forumline_calls SET status = CASE WHEN status = 'ringing' THEN 'missed' ELSE 'completed' END, ended_at = now()
WHERE status IN ('ringing', 'active')
`

func (q *Queries) CleanupStaleCalls(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupStaleCalls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCall = `-- name: CreateCall :one
INSERT INTO forumline_calls (conversation_id, caller_id, callee_id, status)
VALUES ($1, $2, $3, 'ringing')
RETURNING id, conversation_id, caller_id, callee_id, status, created_at
`

type CreateCallParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	CallerID       string    `json:"caller_id"`
	CalleeID       string    `json:"callee_id"`
}

type CreateCallRow struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	CallerID       string    `json:"caller_id"`
	CalleeID       string    `json:"callee_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (CreateCallRow, error) {
	row := q.db.QueryRow(ctx, createCall, arg.ConversationID, arg.CallerID, arg.CalleeID)
	var i CreateCallRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const declineCall = `-- name: DeclineCall :exec
UPDATE forumline_calls SET status = 'declined', ended_at = now() WHERE id = $1
`

func (q *Queries) DeclineCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, declineCall, id)
	return err
}

const endCallWithDuration = `-- name: EndCallWithDuration :exec
UPDATE forumline_calls SET status = $1, ended_at = now(), duration_seconds = EXTRACT(EPOCH FROM now() - started_at)::integer
WHERE id = $2
`

type EndCallWithDurationParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) EndCallWithDuration(ctx context.Context, arg EndCallWithDurationParams) error {
	_, err := q.db.Exec(ctx, endCallWithDuration, arg.Status, arg.ID)
	return err
}

const endCallWithoutDuration = `-- name: EndCallWithoutDuration :exec
UPDATE forumline_calls SET status = $1, ended_at = now() WHERE id = $2
`

type EndCallWithoutDurationParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) EndCallWithoutDuration(ctx context.Context, arg EndCallWithoutDurationParams) error {
	_, err := q.db.Exec(ctx, endCallWithoutDuration, arg.Status, arg.ID)
	return err
}

const getCallForEnd = `-- name: GetCallForEnd :one
SELECT caller_id, callee_id, status, started_at FROM forumline_calls
WHERE id = $1 AND (caller_id = $2 OR callee_id = $2) AND status IN ('ringing', 'active')
`

type GetCallForEndParams struct {
	CallID uuid.UUID `json:"call_id"`
	UserID string    `json:"user_id"`
}

type GetCallForEndRow struct {
	CallerID  string     `json:"caller_id"`
	CalleeID  string     `json:"callee_id"`
	Status    string     `json:"status"`
	StartedAt *time.Time `json:"started_at"`
}

func (q *Queries) GetCallForEnd(ctx context.Context, arg GetCallForEndParams) (GetCallForEndRow, error) {
	row := q.db.QueryRow(ctx, getCallForEnd, arg.CallID, arg.UserID)
	var i GetCallForEndRow
	err := row.Scan(
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.StartedAt,
	)
	return i, err
}

const getCalleeFor1to1 = `-- name: GetCalleeFor1to1 :one
SELECT cm2.user_id FROM forumline_conversations c
JOIN forumline_conversation_members cm1 ON cm1.conversation_id = c.id AND cm1.user_id = $1
JOIN forumline_conversation_members cm2 ON cm2.conversation_id = c.id AND cm2.user_id != $1
WHERE c.id = $2 AND c.is_group = false
AND (SELECT count(*) FROM forumline_conversation_members WHERE conversation_id = c.id) = 2
`

type GetCalleeFor1to1Params struct {
	UserID         string    `json:"user_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

func (q *Queries) GetCalleeFor1to1(ctx context.Context, arg GetCalleeFor1to1Params) (string, error) {
	row := q.db.QueryRow(ctx, getCalleeFor1to1, arg.UserID, arg.ConversationID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getRingingCallCallerID = `-- name: GetRingingCallCallerID :one
SELECT caller_id FROM forumline_calls WHERE id = $1 AND callee_id = $2 AND status = 'ringing'
`

type GetRingingCallCallerIDParams struct {
	ID       uuid.UUID `json:"id"`
	CalleeID string    `json:"callee_id"`
}

func (q *Queries) GetRingingCallCallerID(ctx context.Context, arg GetRingingCallCallerIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getRingingCallCallerID, arg.ID, arg.CalleeID)
	var caller_id string
	err := row.Scan(&caller_id)
	return caller_id, err
}

const hasActiveCall = `-- name: HasActiveCall :one
SELECT EXISTS(SELECT 1 FROM forumline_calls WHERE conversation_id = $1 AND status IN ('ringing', 'active'))
`

func (q *Queries) HasActiveCall(ctx context.Context, conversationID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveCall, conversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isCallParticipant = `-- name: IsCallParticipant :one
SELECT EXISTS(SELECT 1 FROM forumline_calls
WHERE id = $1 AND (caller_id = $2 OR callee_id = $2) AND status IN ('ringing', 'active'))
`

type IsCallParticipantParams struct {
	ID       uuid.UUID `json:"id"`
	CallerID string    `json:"caller_id"`
}

func (q *Queries) IsCallParticipant(ctx context.Context, arg IsCallParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCallParticipant, arg.ID, arg.CallerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserInCall = `-- name: IsUserInCall :one
SELECT EXISTS(SELECT 1 FROM forumline_calls WHERE (caller_id = $1 OR callee_id = $1) AND status IN ('ringing', 'active'))
`

func (q *Queries) IsUserInCall(ctx context.Context, callerID string) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInCall, callerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const notifyCallSignal = `-- name: NotifyCallSignal :exec
SELECT pg_notify('call_signal', $1)
`

func (q *Queries) NotifyCallSignal(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyCallSignal, pgNotify)
	return err
}
