// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMembers = `-- name: AddConversationMembers :exec
INSERT INTO forumline_conversation_members (conversation_id, user_id)
SELECT $1, p.id FROM forumline_profiles p WHERE p.id = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type AddConversationMembersParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberIds      []string  `json:"member_ids"`
}

func (q *Queries) AddConversationMembers(ctx context.Context, arg AddConversationMembersParams) error {
	_, err := q.db.Exec(ctx, addConversationMembers, arg.ConversationID, arg.MemberIds)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO forumline_conversations (is_group, name, created_by) VALUES ($1, $2, $3) RETURNING id
`

type CreateConversationParams struct {
	IsGroup   bool        `json:"is_group"`
	Name      pgtype.Text `json:"name"`
	CreatedBy pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.IsGroup, arg.Name, arg.CreatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const fetchConversationMembers = `-- name: FetchConversationMembers :many
SELECT cm.conversation_id, cm.user_id, p.username, p.display_name, p.avatar_url
FROM forumline_conversation_members cm
JOIN forumline_profiles p ON p.id = cm.user_id
WHERE cm.conversation_id = ANY($1::uuid[])
`

type FetchConversationMembersRow struct {
	ConversationID uuid.UUID   `json:"conversation_id"`
	UserID         string      `json:"user_id"`
	Username       string      `json:"username"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

func (q *Queries) FetchConversationMembers(ctx context.Context, conversationIds []uuid.UUID) ([]FetchConversationMembersRow, error) {
	rows, err := q.db.Query(ctx, fetchConversationMembers, conversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchConversationMembersRow{}
	for rows.Next() {
		var i FetchConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const find1to1Conversation = `-- name: Find1to1Conversation :one
SELECT c.id FROM forumline_conversations c
WHERE c.is_group = false
  AND EXISTS(SELECT 1 FROM forumline_conversation_members cm1 WHERE cm1.conversation_id = c.id AND cm1.user_id = $1)
  AND EXISTS(SELECT 1 FROM forumline_conversation_members cm2 WHERE cm2.conversation_id = c.id AND cm2.user_id = $2)
  AND (SELECT count(*) FROM forumline_conversation_members cm3 WHERE cm3.conversation_id = c.id) = 2
`

type Find1to1ConversationParams struct {
	UserID      string `json:"user_id"`
	OtherUserID string `json:"other_user_id"`
}

func (q *Queries) Find1to1Conversation(ctx context.Context, arg Find1to1ConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, find1to1Conversation, arg.UserID, arg.OtherUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getConversation = `-- name: GetConversation :one
SELECT c.id, c.is_group, c.name,
    COALESCE(m.content, '') AS last_message,
    COALESCE(m.created_at, c.created_at) AS last_message_time,
    (SELECT count(*) FROM forumline_direct_messages dm2
     WHERE dm2.conversation_id = c.id AND dm2.sender_id != $1 AND dm2.created_at > cm.last_read_at)::int AS unread_count
FROM forumline_conversations c
JOIN forumline_conversation_members cm ON cm.conversation_id = c.id AND cm.user_id = $1
LEFT JOIN LATERAL (
    SELECT content, created_at FROM forumline_direct_messages
    WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1
) m ON true
WHERE c.id = $2
`

type GetConversationParams struct {
	UserID         string    `json:"user_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

type GetConversationRow struct {
	ID              uuid.UUID          `json:"id"`
	IsGroup         bool               `json:"is_group"`
	Name            pgtype.Text        `json:"name"`
	LastMessage     string             `json:"last_message"`
	LastMessageTime pgtype.Timestamptz `json:"last_message_time"`
	UnreadCount     int32              `json:"unread_count"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.UserID, arg.ConversationID)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.Name,
		&i.LastMessage,
		&i.LastMessageTime,
		&i.UnreadCount,
	)
	return i, err
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT dm.id, dm.conversation_id, dm.sender_id, dm.content, dm.created_at
FROM forumline_direct_messages dm
WHERE dm.conversation_id = $1 AND dm.created_at < (SELECT dm2.created_at FROM forumline_direct_messages dm2 WHERE dm2.id = $2)
ORDER BY dm.created_at DESC LIMIT $3
`

type GetMessagesBeforeParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	BeforeID       uuid.UUID `json:"before_id"`
	MsgLimit       int32     `json:"msg_limit"`
}

func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]ForumlineDirectMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesBefore, arg.ConversationID, arg.BeforeID, arg.MsgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForumlineDirectMessage{}
	for rows.Next() {
		var i ForumlineDirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesLatest = `-- name: GetMessagesLatest :many
SELECT id, conversation_id, sender_id, content, created_at
FROM forumline_direct_messages
WHERE conversation_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetMessagesLatestParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) GetMessagesLatest(ctx context.Context, arg GetMessagesLatestParams) ([]ForumlineDirectMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesLatest, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForumlineDirectMessage{}
	for rows.Next() {
		var i ForumlineDirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insert1to1Members = `-- name: Insert1to1Members :exec
INSERT INTO forumline_conversation_members (conversation_id, user_id) VALUES ($1, $2), ($1, $3)
`

type Insert1to1MembersParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
	UserID_2       string    `json:"user_id_2"`
}

func (q *Queries) Insert1to1Members(ctx context.Context, arg Insert1to1MembersParams) error {
	_, err := q.db.Exec(ctx, insert1to1Members, arg.ConversationID, arg.UserID, arg.UserID_2)
	return err
}

const insertConversationMember = `-- name: InsertConversationMember :exec
INSERT INTO forumline_conversation_members (conversation_id, user_id) VALUES ($1, $2)
`

type InsertConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) InsertConversationMember(ctx context.Context, arg InsertConversationMemberParams) error {
	_, err := q.db.Exec(ctx, insertConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(SELECT 1 FROM forumline_conversation_members WHERE conversation_id = $1 AND user_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isGroupConversation = `-- name: IsGroupConversation :one
SELECT c.is_group FROM forumline_conversations c
JOIN forumline_conversation_members cm ON cm.conversation_id = c.id AND cm.user_id = $1
WHERE c.id = $2
`

type IsGroupConversationParams struct {
	UserID         string    `json:"user_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

func (q *Queries) IsGroupConversation(ctx context.Context, arg IsGroupConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupConversation, arg.UserID, arg.ConversationID)
	var is_group bool
	err := row.Scan(&is_group)
	return is_group, err
}

const leaveConversation = `-- name: LeaveConversation :exec
DELETE FROM forumline_conversation_members WHERE conversation_id = $1 AND user_id = $2
`

type LeaveConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) LeaveConversation(ctx context.Context, arg LeaveConversationParams) error {
	_, err := q.db.Exec(ctx, leaveConversation, arg.ConversationID, arg.UserID)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id, c.is_group, c.name,
    COALESCE(m.content, '') AS last_message,
    COALESCE(m.created_at, c.created_at) AS last_message_time,
    (SELECT count(*) FROM forumline_direct_messages dm2
     WHERE dm2.conversation_id = c.id
       AND dm2.sender_id != $1
       AND dm2.created_at > cm.last_read_at)::int AS unread_count
FROM forumline_conversations c
JOIN forumline_conversation_members cm ON cm.conversation_id = c.id AND cm.user_id = $1
LEFT JOIN LATERAL (
    SELECT content, created_at FROM forumline_direct_messages
    WHERE conversation_id = c.id
    ORDER BY created_at DESC LIMIT 1
) m ON true
ORDER BY COALESCE(m.created_at, c.created_at) DESC
LIMIT 100
`

type ListConversationsRow struct {
	ID              uuid.UUID          `json:"id"`
	IsGroup         bool               `json:"is_group"`
	Name            pgtype.Text        `json:"name"`
	LastMessage     string             `json:"last_message"`
	LastMessageTime pgtype.Timestamptz `json:"last_message_time"`
	UnreadCount     int32              `json:"unread_count"`
}

func (q *Queries) ListConversations(ctx context.Context, userID string) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.Name,
			&i.LastMessage,
			&i.LastMessageTime,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
UPDATE forumline_conversation_members SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type MarkReadParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         string    `json:"user_id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.Exec(ctx, markRead, arg.ConversationID, arg.UserID)
	return err
}

const removeConversationMembers = `-- name: RemoveConversationMembers :exec
DELETE FROM forumline_conversation_members WHERE conversation_id = $1 AND user_id = ANY($2::text[])
`

type RemoveConversationMembersParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MemberIds      []string  `json:"member_ids"`
}

func (q *Queries) RemoveConversationMembers(ctx context.Context, arg RemoveConversationMembersParams) error {
	_, err := q.db.Exec(ctx, removeConversationMembers, arg.ConversationID, arg.MemberIds)
	return err
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO forumline_direct_messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at
`

type SendMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       string    `json:"sender_id"`
	Content        string    `json:"content"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (ForumlineDirectMessage, error) {
	row := q.db.QueryRow(ctx, sendMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i ForumlineDirectMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE forumline_conversations SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}

const updateConversationName = `-- name: UpdateConversationName :exec
UPDATE forumline_conversations SET name = $1 WHERE id = $2
`

type UpdateConversationNameParams struct {
	Name pgtype.Text `json:"name"`
	ID   uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) error {
	_, err := q.db.Exec(ctx, updateConversationName, arg.Name, arg.ID)
	return err
}
