// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forum.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const autoDeleteUnownedForum = `-- name: AutoDeleteUnownedForum :execrows
DELETE FROM forumline_forums WHERE domain = $1 AND owner_id IS NULL
`

func (q *Queries) AutoDeleteUnownedForum(ctx context.Context, domain string) (int64, error) {
	result, err := q.db.Exec(ctx, autoDeleteUnownedForum, domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countForumMembers = `-- name: CountForumMembers :one
SELECT COUNT(*)::int FROM forumline_memberships WHERE forum_id = $1
`

func (q *Queries) CountForumMembers(ctx context.Context, forumID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countForumMembers, forumID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countForumsByOwner = `-- name: CountForumsByOwner :one
SELECT COUNT(*)::int FROM forumline_forums WHERE owner_id = $1
`

func (q *Queries) CountForumsByOwner(ctx context.Context, ownerID *string) (int32, error) {
	row := q.db.QueryRow(ctx, countForumsByOwner, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteForum = `-- name: DeleteForum :execrows
DELETE FROM forumline_forums WHERE id = $1 AND owner_id = $2
`

type DeleteForumParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID *string   `json:"owner_id"`
}

func (q *Queries) DeleteForum(ctx context.Context, arg DeleteForumParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForum, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForumByID = `-- name: DeleteForumByID :exec
DELETE FROM forumline_forums WHERE id = $1
`

func (q *Queries) DeleteForumByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteForumByID, id)
	return err
}

const delistForum = `-- name: DelistForum :execrows
UPDATE forumline_forums SET approved = false WHERE domain = $1 AND approved = true
`

func (q *Queries) DelistForum(ctx context.Context, domain string) (int64, error) {
	result, err := q.db.Exec(ctx, delistForum, domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const domainExists = `-- name: DomainExists :one
SELECT EXISTS(SELECT 1 FROM forumline_forums WHERE domain = $1)
`

func (q *Queries) DomainExists(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, domainExists, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getForumDomainByID = `-- name: GetForumDomainByID :one
SELECT domain FROM forumline_forums WHERE id = $1
`

func (q *Queries) GetForumDomainByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getForumDomainByID, id)
	var domain string
	err := row.Scan(&domain)
	return domain, err
}

const getForumIDByDomain = `-- name: GetForumIDByDomain :one
SELECT id FROM forumline_forums WHERE domain = $1
`

func (q *Queries) GetForumIDByDomain(ctx context.Context, domain string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getForumIDByDomain, domain)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getForumName = `-- name: GetForumName :one
SELECT COALESCE(name, domain) AS name FROM forumline_forums WHERE id = $1
`

func (q *Queries) GetForumName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getForumName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getForumNameByDomain = `-- name: GetForumNameByDomain :one
SELECT name FROM forumline_forums WHERE domain = $1
`

func (q *Queries) GetForumNameByDomain(ctx context.Context, domain string) (string, error) {
	row := q.db.QueryRow(ctx, getForumNameByDomain, domain)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getForumOwner = `-- name: GetForumOwner :one
SELECT owner_id FROM forumline_forums WHERE id = $1
`

func (q *Queries) GetForumOwner(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getForumOwner, id)
	var owner_id *string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const incrementForumFailures = `-- name: IncrementForumFailures :one
UPDATE forumline_forums SET consecutive_failures = consecutive_failures + 1
WHERE domain = $1 RETURNING consecutive_failures, owner_id
`

type IncrementForumFailuresRow struct {
	ConsecutiveFailures int32   `json:"consecutive_failures"`
	OwnerID             *string `json:"owner_id"`
}

func (q *Queries) IncrementForumFailures(ctx context.Context, domain string) (IncrementForumFailuresRow, error) {
	row := q.db.QueryRow(ctx, incrementForumFailures, domain)
	var i IncrementForumFailuresRow
	err := row.Scan(&i.ConsecutiveFailures, &i.OwnerID)
	return i, err
}

const listAllForums = `-- name: ListAllForums :many
SELECT id, domain, name, icon_url, api_base, web_base, capabilities, approved, owner_id,
       last_seen_at, consecutive_failures
FROM forumline_forums ORDER BY domain
`

type ListAllForumsRow struct {
	ID                  uuid.UUID  `json:"id"`
	Domain              string     `json:"domain"`
	Name                string     `json:"name"`
	IconUrl             *string    `json:"icon_url"`
	ApiBase             string     `json:"api_base"`
	WebBase             string     `json:"web_base"`
	Capabilities        []string   `json:"capabilities"`
	Approved            bool       `json:"approved"`
	OwnerID             *string    `json:"owner_id"`
	LastSeenAt          *time.Time `json:"last_seen_at"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
}

func (q *Queries) ListAllForums(ctx context.Context) ([]ListAllForumsRow, error) {
	rows, err := q.db.Query(ctx, listAllForums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllForumsRow{}
	for rows.Next() {
		var i ListAllForumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.IconUrl,
			&i.ApiBase,
			&i.WebBase,
			&i.Capabilities,
			&i.Approved,
			&i.OwnerID,
			&i.LastSeenAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumTags = `-- name: ListForumTags :many
SELECT DISTINCT unnest(tags) AS tag
FROM forumline_forums WHERE approved = true AND array_length(capabilities, 1) > 0
ORDER BY tag
`

func (q *Queries) ListForumTags(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listForumTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var tag interface{}
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedForums = `-- name: ListOwnedForums :many
SELECT id, domain, name, icon_url, api_base, web_base, approved,
       member_count, last_seen_at, consecutive_failures, created_at
FROM forumline_forums WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListOwnedForumsRow struct {
	ID                  uuid.UUID  `json:"id"`
	Domain              string     `json:"domain"`
	Name                string     `json:"name"`
	IconUrl             *string    `json:"icon_url"`
	ApiBase             string     `json:"api_base"`
	WebBase             string     `json:"web_base"`
	Approved            bool       `json:"approved"`
	MemberCount         int32      `json:"member_count"`
	LastSeenAt          *time.Time `json:"last_seen_at"`
	ConsecutiveFailures int32      `json:"consecutive_failures"`
	CreatedAt           time.Time  `json:"created_at"`
}

func (q *Queries) ListOwnedForums(ctx context.Context, ownerID *string) ([]ListOwnedForumsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedForums, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedForumsRow{}
	for rows.Next() {
		var i ListOwnedForumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.IconUrl,
			&i.ApiBase,
			&i.WebBase,
			&i.Approved,
			&i.MemberCount,
			&i.LastSeenAt,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendedForums = `-- name: ListRecommendedForums :many
WITH my_forums AS (
    SELECT ms.forum_id FROM forumline_memberships ms WHERE ms.user_id = $1
),
forum_mates AS (
    SELECT DISTINCT m.user_id
    FROM forumline_memberships m
    JOIN my_forums mf ON m.forum_id = mf.forum_id
    WHERE m.user_id != $1
)
SELECT f.id, f.domain, f.name, f.icon_url, f.api_base, f.web_base,
       f.capabilities, f.description, f.screenshot_url, f.tags, f.member_count,
       COUNT(m2.user_id)::int AS shared_member_count
FROM forumline_memberships m2
JOIN forum_mates fm ON m2.user_id = fm.user_id
JOIN forumline_forums f ON f.id = m2.forum_id
WHERE f.approved = true
  AND f.id NOT IN (SELECT mf2.forum_id FROM my_forums mf2)
GROUP BY f.id
ORDER BY shared_member_count DESC, f.member_count DESC
LIMIT 10
`

type ListRecommendedForumsRow struct {
	ID                uuid.UUID `json:"id"`
	Domain            string    `json:"domain"`
	Name              string    `json:"name"`
	IconUrl           *string   `json:"icon_url"`
	ApiBase           string    `json:"api_base"`
	WebBase           string    `json:"web_base"`
	Capabilities      []string  `json:"capabilities"`
	Description       *string   `json:"description"`
	ScreenshotUrl     *string   `json:"screenshot_url"`
	Tags              []string  `json:"tags"`
	MemberCount       int32     `json:"member_count"`
	SharedMemberCount int32     `json:"shared_member_count"`
}

func (q *Queries) ListRecommendedForums(ctx context.Context, userID string) ([]ListRecommendedForumsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendedForums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendedForumsRow{}
	for rows.Next() {
		var i ListRecommendedForumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.IconUrl,
			&i.ApiBase,
			&i.WebBase,
			&i.Capabilities,
			&i.Description,
			&i.ScreenshotUrl,
			&i.Tags,
			&i.MemberCount,
			&i.SharedMemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markForumHealthy = `-- name: MarkForumHealthy :execrows
UPDATE forumline_forums SET last_seen_at = now(), consecutive_failures = 0 WHERE domain = $1
`

func (q *Queries) MarkForumHealthy(ctx context.Context, domain string) (int64, error) {
	result, err := q.db.Exec(ctx, markForumHealthy, domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapproveHealthyForum = `-- name: ReapproveHealthyForum :exec
UPDATE forumline_forums SET approved = true
WHERE domain = $1 AND approved = false AND consecutive_failures = 0 AND owner_id IS NOT NULL
`

func (q *Queries) ReapproveHealthyForum(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, reapproveHealthyForum, domain)
	return err
}

const registerForum = `-- name: RegisterForum :one
INSERT INTO forumline_forums (domain, name, api_base, web_base, capabilities, description, tags, owner_id, approved)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, false)
RETURNING id
`

type RegisterForumParams struct {
	Domain       string   `json:"domain"`
	Name         string   `json:"name"`
	ApiBase      string   `json:"api_base"`
	WebBase      string   `json:"web_base"`
	Capabilities []string `json:"capabilities"`
	Description  *string  `json:"description"`
	Tags         []string `json:"tags"`
	OwnerID      *string  `json:"owner_id"`
}

func (q *Queries) RegisterForum(ctx context.Context, arg RegisterForumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, registerForum,
		arg.Domain,
		arg.Name,
		arg.ApiBase,
		arg.WebBase,
		arg.Capabilities,
		arg.Description,
		arg.Tags,
		arg.OwnerID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateForumIcon = `-- name: UpdateForumIcon :execrows
UPDATE forumline_forums SET icon_url = $1, updated_at = now() WHERE domain = $2
`

type UpdateForumIconParams struct {
	IconUrl *string `json:"icon_url"`
	Domain  string  `json:"domain"`
}

func (q *Queries) UpdateForumIcon(ctx context.Context, arg UpdateForumIconParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateForumIcon, arg.IconUrl, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateForumScreenshot = `-- name: UpdateForumScreenshot :execrows
UPDATE forumline_forums SET screenshot_url = $1, updated_at = now() WHERE domain = $2
`

type UpdateForumScreenshotParams struct {
	ScreenshotUrl *string `json:"screenshot_url"`
	Domain        string  `json:"domain"`
}

func (q *Queries) UpdateForumScreenshot(ctx context.Context, arg UpdateForumScreenshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateForumScreenshot, arg.ScreenshotUrl, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertForumFromManifest = `-- name: UpsertForumFromManifest :one
INSERT INTO forumline_forums (domain, name, icon_url, api_base, web_base, capabilities, tags, approved)
VALUES ($1, $2, $3, $4, $5, $6, $7, false)
ON CONFLICT (domain) DO UPDATE SET
  name = EXCLUDED.name, icon_url = EXCLUDED.icon_url,
  api_base = EXCLUDED.api_base, web_base = EXCLUDED.web_base,
  capabilities = EXCLUDED.capabilities, tags = EXCLUDED.tags
WHERE forumline_forums.approved = false
RETURNING id
`

type UpsertForumFromManifestParams struct {
	Domain       string   `json:"domain"`
	Name         string   `json:"name"`
	IconUrl      *string  `json:"icon_url"`
	ApiBase      string   `json:"api_base"`
	WebBase      string   `json:"web_base"`
	Capabilities []string `json:"capabilities"`
	Tags         []string `json:"tags"`
}

func (q *Queries) UpsertForumFromManifest(ctx context.Context, arg UpsertForumFromManifestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertForumFromManifest,
		arg.Domain,
		arg.Name,
		arg.IconUrl,
		arg.ApiBase,
		arg.WebBase,
		arg.Capabilities,
		arg.Tags,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
