// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: membership.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMembershipAuthed = `-- name: ClearMembershipAuthed :exec
UPDATE forumline_memberships SET forum_authed_at = NULL WHERE user_id = $1 AND forum_id = $2
`

type ClearMembershipAuthedParams struct {
	UserID  string      `json:"user_id"`
	ForumID pgtype.UUID `json:"forum_id"`
}

func (q *Queries) ClearMembershipAuthed(ctx context.Context, arg ClearMembershipAuthedParams) error {
	_, err := q.db.Exec(ctx, clearMembershipAuthed, arg.UserID, arg.ForumID)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM forumline_memberships WHERE user_id = $1 AND forum_id = $2
`

type DeleteMembershipParams struct {
	UserID  string      `json:"user_id"`
	ForumID pgtype.UUID `json:"forum_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.ForumID)
	return err
}

const getMembershipJoinDetails = `-- name: GetMembershipJoinDetails :one
SELECT f.domain, f.name, f.icon_url, f.api_base, f.web_base, f.capabilities, m.joined_at,
       (SELECT COUNT(*)::int FROM forumline_memberships WHERE forum_id = f.id) AS member_count
FROM forumline_forums f
JOIN forumline_memberships m ON m.forum_id = f.id
WHERE f.id = $1 AND m.user_id = $2
`

type GetMembershipJoinDetailsParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetMembershipJoinDetailsRow struct {
	Domain       string             `json:"domain"`
	Name         string             `json:"name"`
	IconUrl      pgtype.Text        `json:"icon_url"`
	ApiBase      string             `json:"api_base"`
	WebBase      string             `json:"web_base"`
	Capabilities []string           `json:"capabilities"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	MemberCount  int32              `json:"member_count"`
}

func (q *Queries) GetMembershipJoinDetails(ctx context.Context, arg GetMembershipJoinDetailsParams) (GetMembershipJoinDetailsRow, error) {
	row := q.db.QueryRow(ctx, getMembershipJoinDetails, arg.ID, arg.UserID)
	var i GetMembershipJoinDetailsRow
	err := row.Scan(
		&i.Domain,
		&i.Name,
		&i.IconUrl,
		&i.ApiBase,
		&i.WebBase,
		&i.Capabilities,
		&i.JoinedAt,
		&i.MemberCount,
	)
	return i, err
}

const isNotificationsMuted = `-- name: IsNotificationsMuted :one
SELECT notifications_muted FROM forumline_memberships WHERE user_id = $1 AND forum_id = $2
`

type IsNotificationsMutedParams struct {
	UserID  string      `json:"user_id"`
	ForumID pgtype.UUID `json:"forum_id"`
}

func (q *Queries) IsNotificationsMuted(ctx context.Context, arg IsNotificationsMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationsMuted, arg.UserID, arg.ForumID)
	var notifications_muted bool
	err := row.Scan(&notifications_muted)
	return notifications_muted, err
}

const isNotificationsMutedByDomain = `-- name: IsNotificationsMutedByDomain :one
SELECT m.notifications_muted
FROM forumline_memberships m
JOIN forumline_forums f ON f.id = m.forum_id
WHERE m.user_id = $1 AND f.domain = $2
`

type IsNotificationsMutedByDomainParams struct {
	UserID string `json:"user_id"`
	Domain string `json:"domain"`
}

func (q *Queries) IsNotificationsMutedByDomain(ctx context.Context, arg IsNotificationsMutedByDomainParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationsMutedByDomain, arg.UserID, arg.Domain)
	var notifications_muted bool
	err := row.Scan(&notifications_muted)
	return notifications_muted, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT m.id, m.joined_at, m.forum_authed_at, m.notifications_muted,
       f.domain, f.name, f.icon_url, f.api_base, f.web_base, f.capabilities,
       f.member_count
FROM forumline_memberships m
JOIN forumline_forums f ON f.id = m.forum_id
WHERE m.user_id = $1
ORDER BY m.joined_at DESC
`

type ListMembershipsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	JoinedAt           pgtype.Timestamptz `json:"joined_at"`
	ForumAuthedAt      pgtype.Timestamptz `json:"forum_authed_at"`
	NotificationsMuted bool               `json:"notifications_muted"`
	Domain             string             `json:"domain"`
	Name               string             `json:"name"`
	IconUrl            pgtype.Text        `json:"icon_url"`
	ApiBase            string             `json:"api_base"`
	WebBase            string             `json:"web_base"`
	Capabilities       []string           `json:"capabilities"`
	MemberCount        int32              `json:"member_count"`
}

func (q *Queries) ListMemberships(ctx context.Context, userID string) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.JoinedAt,
			&i.ForumAuthedAt,
			&i.NotificationsMuted,
			&i.Domain,
			&i.Name,
			&i.IconUrl,
			&i.ApiBase,
			&i.WebBase,
			&i.Capabilities,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMembershipAuthed = `-- name: SetMembershipAuthed :exec
UPDATE forumline_memberships SET forum_authed_at = now() WHERE user_id = $1 AND forum_id = $2
`

type SetMembershipAuthedParams struct {
	UserID  string      `json:"user_id"`
	ForumID pgtype.UUID `json:"forum_id"`
}

func (q *Queries) SetMembershipAuthed(ctx context.Context, arg SetMembershipAuthedParams) error {
	_, err := q.db.Exec(ctx, setMembershipAuthed, arg.UserID, arg.ForumID)
	return err
}

const updateMembershipMute = `-- name: UpdateMembershipMute :exec
UPDATE forumline_memberships SET notifications_muted = $1 WHERE user_id = $2 AND forum_id = $3
`

type UpdateMembershipMuteParams struct {
	NotificationsMuted bool        `json:"notifications_muted"`
	UserID             string      `json:"user_id"`
	ForumID            pgtype.UUID `json:"forum_id"`
}

func (q *Queries) UpdateMembershipMute(ctx context.Context, arg UpdateMembershipMuteParams) error {
	_, err := q.db.Exec(ctx, updateMembershipMute, arg.NotificationsMuted, arg.UserID, arg.ForumID)
	return err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO forumline_memberships (user_id, forum_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type UpsertMembershipParams struct {
	UserID  string      `json:"user_id"`
	ForumID pgtype.UUID `json:"forum_id"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership, arg.UserID, arg.ForumID)
	return err
}
