// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::int FROM forumline_notifications WHERE user_id = $1 AND read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO forumline_notifications (user_id, forum_domain, forum_name, type, title, body, link)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	UserID      string `json:"user_id"`
	ForumDomain string `json:"forum_domain"`
	ForumName   string `json:"forum_name"`
	Type        string `json:"type"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Link        string `json:"link"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.ForumDomain,
		arg.ForumName,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, forum_domain, forum_name, type, title, body, link, read, created_at
FROM forumline_notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListNotificationsRow struct {
	ID          uuid.UUID `json:"id"`
	ForumDomain string    `json:"forum_domain"`
	ForumName   string    `json:"forum_name"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	Link        string    `json:"link"`
	Read        bool      `json:"read"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ForumDomain,
			&i.ForumName,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE forumline_notifications SET read = true WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE forumline_notifications SET read = true WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
