// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package sqlcdb

import (
	"context"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   string `json:"user_id"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const deleteStaleEndpoints = `-- name: DeleteStaleEndpoints :exec
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = ANY($2::text[])
`

type DeleteStaleEndpointsParams struct {
	UserID    string   `json:"user_id"`
	Endpoints []string `json:"endpoints"`
}

func (q *Queries) DeleteStaleEndpoints(ctx context.Context, arg DeleteStaleEndpointsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleEndpoints, arg.UserID, arg.Endpoints)
	return err
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT endpoint, p256dh, auth FROM push_subscriptions WHERE user_id = $1
`

type ListPushSubscriptionsRow struct {
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID string) ([]ListPushSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushSubscriptionsRow{}
	for rows.Next() {
		var i ListPushSubscriptionsRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, endpoint) DO UPDATE SET p256dh = $3, auth = $4
`

type UpsertPushSubscriptionParams struct {
	UserID   string `json:"user_id"`
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
