// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmark.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBookmark = `-- name: AddBookmark :exec
INSERT INTO bookmarks (user_id, thread_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddBookmarkParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ThreadID uuid.UUID `json:"thread_id"`
}

func (q *Queries) AddBookmark(ctx context.Context, arg AddBookmarkParams) error {
	_, err := q.db.Exec(ctx, addBookmark, arg.UserID, arg.ThreadID)
	return err
}

const getBookmarkStatus = `-- name: GetBookmarkStatus :one
SELECT id FROM bookmarks WHERE user_id = $1 AND thread_id = $2
`

type GetBookmarkStatusParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ThreadID uuid.UUID `json:"thread_id"`
}

func (q *Queries) GetBookmarkStatus(ctx context.Context, arg GetBookmarkStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBookmarkStatus, arg.UserID, arg.ThreadID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT b.id, b.created_at AS bookmark_created_at,
       t.id AS thread_id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at AS thread_created_at, t.updated_at AS thread_updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM bookmarks b
JOIN threads t ON t.id = b.thread_id
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type ListBookmarksRow struct {
	ID                uuid.UUID          `json:"id"`
	BookmarkCreatedAt pgtype.Timestamptz `json:"bookmark_created_at"`
	ThreadID          uuid.UUID          `json:"thread_id"`
	CategoryID        uuid.UUID          `json:"category_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	Content           pgtype.Text        `json:"content"`
	ImageUrl          pgtype.Text        `json:"image_url"`
	IsPinned          bool               `json:"is_pinned"`
	IsLocked          bool               `json:"is_locked"`
	ViewCount         int32              `json:"view_count"`
	PostCount         int32              `json:"post_count"`
	LastPostAt        pgtype.Timestamptz `json:"last_post_at"`
	ThreadCreatedAt   pgtype.Timestamptz `json:"thread_created_at"`
	ThreadUpdatedAt   pgtype.Timestamptz `json:"thread_updated_at"`
	AuthorID2         uuid.UUID          `json:"author_id_2"`
	AuthorUsername    string             `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	AuthorBio         pgtype.Text        `json:"author_bio"`
	AuthorWebsite     pgtype.Text        `json:"author_website"`
	AuthorIsAdmin     bool               `json:"author_is_admin"`
	AuthorForumlineID pgtype.Text        `json:"author_forumline_id"`
	AuthorCreatedAt   pgtype.Timestamptz `json:"author_created_at"`
	AuthorUpdatedAt   pgtype.Timestamptz `json:"author_updated_at"`
	CatID             uuid.UUID          `json:"cat_id"`
	CatName           string             `json:"cat_name"`
	CatSlug           string             `json:"cat_slug"`
	CatDescription    pgtype.Text        `json:"cat_description"`
	CatSortOrder      int32              `json:"cat_sort_order"`
	CatCreatedAt      pgtype.Timestamptz `json:"cat_created_at"`
}

func (q *Queries) ListBookmarks(ctx context.Context, userID uuid.UUID) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookmarkCreatedAt,
			&i.ThreadID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.ViewCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.ThreadCreatedAt,
			&i.ThreadUpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.CatID,
			&i.CatName,
			&i.CatSlug,
			&i.CatDescription,
			&i.CatSortOrder,
			&i.CatCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookmark = `-- name: RemoveBookmark :exec
DELETE FROM bookmarks WHERE user_id = $1 AND thread_id = $2
`

type RemoveBookmarkParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ThreadID uuid.UUID `json:"thread_id"`
}

func (q *Queries) RemoveBookmark(ctx context.Context, arg RemoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, removeBookmark, arg.UserID, arg.ThreadID)
	return err
}

const removeBookmarkByID = `-- name: RemoveBookmarkByID :exec
DELETE FROM bookmarks WHERE id = $1 AND user_id = $2
`

type RemoveBookmarkByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveBookmarkByID(ctx context.Context, arg RemoveBookmarkByIDParams) error {
	_, err := q.db.Exec(ctx, removeBookmarkByID, arg.ID, arg.UserID)
	return err
}
