// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChannelIDBySlug = `-- name: GetChannelIDBySlug :one
SELECT id FROM chat_channels WHERE slug = $1
`

func (q *Queries) GetChannelIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChannelIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertChatMessage = `-- name: InsertChatMessage :exec
INSERT INTO chat_messages (channel_id, author_id, content) VALUES ($1, $2, $3)
`

type InsertChatMessageParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	AuthorID  uuid.UUID `json:"author_id"`
	Content   string    `json:"content"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) error {
	_, err := q.db.Exec(ctx, insertChatMessage, arg.ChannelID, arg.AuthorID, arg.Content)
	return err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, slug, description, created_at
FROM chat_channels ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context) ([]ChatChannel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatChannel{}
	for rows.Next() {
		var i ChatChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT m.id, m.channel_id, m.author_id, m.content, m.created_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at
FROM chat_messages m
JOIN chat_channels ch ON ch.id = m.channel_id
JOIN profiles p ON p.id = m.author_id
WHERE ch.slug = $1
ORDER BY m.created_at ASC
LIMIT 100
`

type ListChatMessagesRow struct {
	ID                uuid.UUID `json:"id"`
	ChannelID         uuid.UUID `json:"channel_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Content           string    `json:"content"`
	CreatedAt         time.Time `json:"created_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
}

func (q *Queries) ListChatMessages(ctx context.Context, slug string) ([]ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatMessagesRow{}
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
