// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misc.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelFollow = `-- name: AddChannelFollow :exec
INSERT INTO channel_follows (user_id, category_id)
VALUES ($1, $2)
ON CONFLICT (user_id, category_id) DO NOTHING
`

type AddChannelFollowParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) AddChannelFollow(ctx context.Context, arg AddChannelFollowParams) error {
	_, err := q.db.Exec(ctx, addChannelFollow, arg.UserID, arg.CategoryID)
	return err
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*)::int FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countProfiles = `-- name: CountProfiles :one
SELECT COUNT(*)::int FROM profiles
`

func (q *Queries) CountProfiles(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countProfiles)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countThreads = `-- name: CountThreads :one
SELECT COUNT(*)::int FROM threads
`

func (q *Queries) CountThreads(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countThreads)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listChannelFollows = `-- name: ListChannelFollows :many
SELECT category_id FROM channel_follows WHERE user_id = $1
`

func (q *Queries) ListChannelFollows(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listChannelFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPrefs = `-- name: ListNotificationPrefs :many
SELECT category, enabled FROM notification_preferences WHERE user_id = $1
`

type ListNotificationPrefsRow struct {
	Category string `json:"category"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) ListNotificationPrefs(ctx context.Context, userID pgtype.UUID) ([]ListNotificationPrefsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationPrefs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationPrefsRow{}
	for rows.Next() {
		var i ListNotificationPrefsRow
		if err := rows.Scan(&i.Category, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelFollow = `-- name: RemoveChannelFollow :exec
DELETE FROM channel_follows WHERE user_id = $1 AND category_id = $2
`

type RemoveChannelFollowParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) RemoveChannelFollow(ctx context.Context, arg RemoveChannelFollowParams) error {
	_, err := q.db.Exec(ctx, removeChannelFollow, arg.UserID, arg.CategoryID)
	return err
}

const upsertNotificationPref = `-- name: UpsertNotificationPref :exec
INSERT INTO notification_preferences (user_id, category, enabled, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category)
DO UPDATE SET enabled = $3, updated_at = $4
`

type UpsertNotificationPrefParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Category  string             `json:"category"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertNotificationPref(ctx context.Context, arg UpsertNotificationPrefParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPref,
		arg.UserID,
		arg.Category,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}
