// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ThreadID  uuid.UUID          `json:"thread_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChannelFollow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CategoryID uuid.UUID          `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChatChannel struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID        uuid.UUID          `json:"id"`
	ChannelID uuid.UUID          `json:"channel_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	Link      pgtype.Text        `json:"link"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Category  string             `json:"category"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Post struct {
	ID        uuid.UUID          `json:"id"`
	ThreadID  uuid.UUID          `json:"thread_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Content   string             `json:"content"`
	ReplyToID *uuid.UUID         `json:"reply_to_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Bio         pgtype.Text        `json:"bio"`
	Website     pgtype.Text        `json:"website"`
	IsAdmin     bool               `json:"is_admin"`
	ForumlineID pgtype.Text        `json:"forumline_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Thread struct {
	ID         uuid.UUID          `json:"id"`
	CategoryID uuid.UUID          `json:"category_id"`
	AuthorID   uuid.UUID          `json:"author_id"`
	Title      string             `json:"title"`
	Slug       string             `json:"slug"`
	Content    pgtype.Text        `json:"content"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	IsPinned   bool               `json:"is_pinned"`
	IsLocked   bool               `json:"is_locked"`
	ViewCount  int32              `json:"view_count"`
	PostCount  int32              `json:"post_count"`
	LastPostAt pgtype.Timestamptz `json:"last_post_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type VoicePresence struct {
	ID       uuid.UUID          `json:"id"`
	UserID   uuid.UUID          `json:"user_id"`
	RoomSlug string             `json:"room_slug"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type VoiceRoom struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
