// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadChatMentions = `-- name: CountUnreadChatMentions :one
SELECT COUNT(*)::int FROM notifications
WHERE user_id = $1 AND read = false AND type = 'chat_mention'
`

func (q *Queries) CountUnreadChatMentions(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadChatMentions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::int FROM notifications
WHERE user_id = $1 AND read = false AND type != 'chat_mention'
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getThreadTitleAndAuthor = `-- name: GetThreadTitleAndAuthor :one
SELECT t.title, p.author_id FROM threads t
JOIN posts p ON p.thread_id = t.id
WHERE t.id = $1 ORDER BY p.created_at ASC LIMIT 1
`

type GetThreadTitleAndAuthorRow struct {
	Title    string    `json:"title"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) GetThreadTitleAndAuthor(ctx context.Context, id uuid.UUID) (GetThreadTitleAndAuthorRow, error) {
	row := q.db.QueryRow(ctx, getThreadTitleAndAuthor, id)
	var i GetThreadTitleAndAuthorRow
	err := row.Scan(&i.Title, &i.AuthorID)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (user_id, type, title, message, link)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Type    string    `json:"type"`
	Title   string    `json:"title"`
	Message string    `json:"message"`
	Link    *string   `json:"link"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Link,
	)
	return err
}

const listForumlineNotifications = `-- name: ListForumlineNotifications :many
SELECT id, type, title, message, link, read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListForumlineNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListForumlineNotificationsRow struct {
	ID        uuid.UUID `json:"id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	Link      *string   `json:"link"`
	Read      bool      `json:"read"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListForumlineNotifications(ctx context.Context, arg ListForumlineNotificationsParams) ([]ListForumlineNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listForumlineNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumlineNotificationsRow{}
	for rows.Next() {
		var i ListForumlineNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, message, link, read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = true WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read = true WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
