// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (thread_id, author_id, content, reply_to_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id
`

type CreatePostParams struct {
	ThreadID  uuid.UUID          `json:"thread_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Content   string             `json:"content"`
	ReplyToID *uuid.UUID         `json:"reply_to_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ThreadID,
		arg.AuthorID,
		arg.Content,
		arg.ReplyToID,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPostAuthor = `-- name: GetPostAuthor :one
SELECT author_id FROM posts WHERE id = $1
`

func (q *Queries) GetPostAuthor(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPostAuthor, id)
	var author_id uuid.UUID
	err := row.Scan(&author_id)
	return author_id, err
}

const listPostsByThread = `-- name: ListPostsByThread :many
SELECT po.id, po.thread_id, po.author_id, po.content, po.reply_to_id, po.created_at, po.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at
FROM posts po
JOIN profiles p ON p.id = po.author_id
WHERE po.thread_id = $1 ORDER BY po.created_at ASC
`

type ListPostsByThreadRow struct {
	ID                uuid.UUID          `json:"id"`
	ThreadID          uuid.UUID          `json:"thread_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Content           string             `json:"content"`
	ReplyToID         *uuid.UUID         `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AuthorID2         uuid.UUID          `json:"author_id_2"`
	AuthorUsername    string             `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	AuthorBio         pgtype.Text        `json:"author_bio"`
	AuthorWebsite     pgtype.Text        `json:"author_website"`
	AuthorIsAdmin     bool               `json:"author_is_admin"`
	AuthorForumlineID pgtype.Text        `json:"author_forumline_id"`
	AuthorCreatedAt   pgtype.Timestamptz `json:"author_created_at"`
	AuthorUpdatedAt   pgtype.Timestamptz `json:"author_updated_at"`
}

func (q *Queries) ListPostsByThread(ctx context.Context, threadID uuid.UUID) ([]ListPostsByThreadRow, error) {
	rows, err := q.db.Query(ctx, listPostsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByThreadRow{}
	for rows.Next() {
		var i ListPostsByThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPosts = `-- name: ListUserPosts :many
SELECT po.id, po.thread_id, po.author_id, po.content, po.reply_to_id, po.created_at, po.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at
FROM posts po
JOIN profiles p ON p.id = po.author_id
WHERE po.author_id = $1 ORDER BY po.created_at DESC LIMIT 20
`

type ListUserPostsRow struct {
	ID                uuid.UUID          `json:"id"`
	ThreadID          uuid.UUID          `json:"thread_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Content           string             `json:"content"`
	ReplyToID         *uuid.UUID         `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AuthorID2         uuid.UUID          `json:"author_id_2"`
	AuthorUsername    string             `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	AuthorBio         pgtype.Text        `json:"author_bio"`
	AuthorWebsite     pgtype.Text        `json:"author_website"`
	AuthorIsAdmin     bool               `json:"author_is_admin"`
	AuthorForumlineID pgtype.Text        `json:"author_forumline_id"`
	AuthorCreatedAt   pgtype.Timestamptz `json:"author_created_at"`
	AuthorUpdatedAt   pgtype.Timestamptz `json:"author_updated_at"`
}

func (q *Queries) ListUserPosts(ctx context.Context, authorID uuid.UUID) ([]ListUserPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserPosts, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPostsRow{}
	for rows.Next() {
		var i ListUserPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT po.id, po.thread_id, po.author_id, po.content, po.reply_to_id, po.created_at, po.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at
FROM posts po
JOIN profiles p ON p.id = po.author_id
WHERE po.content ILIKE $1 ORDER BY po.created_at DESC LIMIT 20
`

type SearchPostsRow struct {
	ID                uuid.UUID          `json:"id"`
	ThreadID          uuid.UUID          `json:"thread_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Content           string             `json:"content"`
	ReplyToID         *uuid.UUID         `json:"reply_to_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AuthorID2         uuid.UUID          `json:"author_id_2"`
	AuthorUsername    string             `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	AuthorBio         pgtype.Text        `json:"author_bio"`
	AuthorWebsite     pgtype.Text        `json:"author_website"`
	AuthorIsAdmin     bool               `json:"author_is_admin"`
	AuthorForumlineID pgtype.Text        `json:"author_forumline_id"`
	AuthorCreatedAt   pgtype.Timestamptz `json:"author_created_at"`
	AuthorUpdatedAt   pgtype.Timestamptz `json:"author_updated_at"`
}

func (q *Queries) SearchPosts(ctx context.Context, content string) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
