// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearForumlineID = `-- name: ClearForumlineID :exec
UPDATE profiles SET forumline_id = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ClearForumlineID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearForumlineID, id)
	return err
}

const createProfileHosted = `-- name: CreateProfileHosted :exec
INSERT INTO profiles (id, username, display_name, avatar_url, forumline_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET forumline_id = $5, display_name = $3
`

type CreateProfileHostedParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ForumlineID pgtype.Text `json:"forumline_id"`
}

func (q *Queries) CreateProfileHosted(ctx context.Context, arg CreateProfileHostedParams) error {
	_, err := q.db.Exec(ctx, createProfileHosted,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ForumlineID,
	)
	return err
}

const createProfileSimple = `-- name: CreateProfileSimple :exec
INSERT INTO profiles (id, username, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET username = $2, display_name = $3
`

type CreateProfileSimpleParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateProfileSimple(ctx context.Context, arg CreateProfileSimpleParams) error {
	_, err := q.db.Exec(ctx, createProfileSimple, arg.ID, arg.Username, arg.DisplayName)
	return err
}

const ensureProfileWithForumlineID = `-- name: EnsureProfileWithForumlineID :exec
INSERT INTO profiles (id, username, display_name, forumline_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET forumline_id = $4, display_name = $3
`

type EnsureProfileWithForumlineIDParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	ForumlineID pgtype.Text `json:"forumline_id"`
}

func (q *Queries) EnsureProfileWithForumlineID(ctx context.Context, arg EnsureProfileWithForumlineIDParams) error {
	_, err := q.db.Exec(ctx, ensureProfileWithForumlineID,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.ForumlineID,
	)
	return err
}

const getForumlineID = `-- name: GetForumlineID :one
SELECT forumline_id FROM profiles WHERE id = $1
`

func (q *Queries) GetForumlineID(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getForumlineID, id)
	var forumline_id pgtype.Text
	err := row.Scan(&forumline_id)
	return forumline_id, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, username, display_name, avatar_url, bio, website, is_admin, forumline_id, created_at, updated_at
FROM profiles WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Website,
		&i.IsAdmin,
		&i.ForumlineID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, username, display_name, avatar_url, bio, website, is_admin, forumline_id, created_at, updated_at
FROM profiles WHERE username = $1
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Website,
		&i.IsAdmin,
		&i.ForumlineID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileIDByForumlineID = `-- name: GetProfileIDByForumlineID :one
SELECT id FROM profiles WHERE forumline_id = $1
`

func (q *Queries) GetProfileIDByForumlineID(ctx context.Context, forumlineID pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProfileIDByForumlineID, forumlineID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProfileIDByForumlineIDUnlinked = `-- name: GetProfileIDByForumlineIDUnlinked :one
SELECT id FROM profiles WHERE id = $1 AND (forumline_id IS NULL OR forumline_id = '')
`

func (q *Queries) GetProfileIDByForumlineIDUnlinked(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProfileIDByForumlineIDUnlinked, id)
	err := row.Scan(&id)
	return id, err
}

const getProfilesByIDs = `-- name: GetProfilesByIDs :many
SELECT id, username, display_name, avatar_url, bio, website, is_admin, forumline_id, created_at, updated_at
FROM profiles WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProfilesByIDs(ctx context.Context, ids []uuid.UUID) ([]Profile, error) {
	rows, err := q.db.Query(ctx, getProfilesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Website,
			&i.IsAdmin,
			&i.ForumlineID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByUsername = `-- name: GetUserIDByUsername :one
SELECT id FROM profiles WHERE lower(username) = $1
`

func (q *Queries) GetUserIDByUsername(ctx context.Context, username string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByUsername, username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUsername = `-- name: GetUsername :one
SELECT username FROM profiles WHERE id = $1
`

func (q *Queries) GetUsername(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT is_admin FROM profiles WHERE id = $1
`

func (q *Queries) IsAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, username, display_name, avatar_url, bio, website, is_admin, forumline_id, created_at, updated_at
FROM profiles ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListProfiles(ctx context.Context, limit int32) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Website,
			&i.IsAdmin,
			&i.ForumlineID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setForumlineID = `-- name: SetForumlineID :exec
UPDATE profiles SET forumline_id = $1 WHERE id = $2
`

type SetForumlineIDParams struct {
	ForumlineID pgtype.Text `json:"forumline_id"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) SetForumlineID(ctx context.Context, arg SetForumlineIDParams) error {
	_, err := q.db.Exec(ctx, setForumlineID, arg.ForumlineID, arg.ID)
	return err
}

const updateDisplayName = `-- name: UpdateDisplayName :exec
UPDATE profiles SET display_name = $1 WHERE id = $2
`

type UpdateDisplayNameParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateDisplayNameAndAvatar = `-- name: UpdateDisplayNameAndAvatar :exec
UPDATE profiles SET display_name = $1, avatar_url = $2, updated_at = now() WHERE id = $3
`

type UpdateDisplayNameAndAvatarParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDisplayNameAndAvatar(ctx context.Context, arg UpdateDisplayNameAndAvatarParams) error {
	_, err := q.db.Exec(ctx, updateDisplayNameAndAvatar, arg.DisplayName, arg.AvatarUrl, arg.ID)
	return err
}

const upsertProfileFull = `-- name: UpsertProfileFull :exec
INSERT INTO profiles (id, username, display_name, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (id) DO UPDATE SET
  username = EXCLUDED.username,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  updated_at = EXCLUDED.updated_at
`

type UpsertProfileFullParams struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertProfileFull(ctx context.Context, arg UpsertProfileFullParams) error {
	_, err := q.db.Exec(ctx, upsertProfileFull,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM profiles WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
