// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thread.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (category_id, author_id, title, slug, content, image_url, post_count, last_post_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7, $7, $7)
RETURNING id
`

type CreateThreadParams struct {
	CategoryID uuid.UUID  `json:"category_id"`
	AuthorID   uuid.UUID  `json:"author_id"`
	Title      string     `json:"title"`
	Slug       string     `json:"slug"`
	Content    *string    `json:"content"`
	ImageUrl   *string    `json:"image_url"`
	LastPostAt *time.Time `json:"last_post_at"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.CategoryID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.ImageUrl,
		arg.LastPostAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getThread = `-- name: GetThread :one
SELECT t.id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at, t.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM threads t
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
WHERE t.id = $1
`

type GetThreadRow struct {
	ID                uuid.UUID `json:"id"`
	CategoryID        uuid.UUID `json:"category_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Title             string    `json:"title"`
	Slug              string    `json:"slug"`
	Content           *string   `json:"content"`
	ImageUrl          *string   `json:"image_url"`
	IsPinned          bool      `json:"is_pinned"`
	IsLocked          bool      `json:"is_locked"`
	ViewCount         int32     `json:"view_count"`
	PostCount         int32     `json:"post_count"`
	LastPostAt        time.Time `json:"last_post_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
	CatID             uuid.UUID `json:"cat_id"`
	CatName           string    `json:"cat_name"`
	CatSlug           string    `json:"cat_slug"`
	CatDescription    *string   `json:"cat_description"`
	CatSortOrder      int32     `json:"cat_sort_order"`
	CatCreatedAt      time.Time `json:"cat_created_at"`
}

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ImageUrl,
		&i.IsPinned,
		&i.IsLocked,
		&i.ViewCount,
		&i.PostCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID2,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.AuthorBio,
		&i.AuthorWebsite,
		&i.AuthorIsAdmin,
		&i.AuthorForumlineID,
		&i.AuthorCreatedAt,
		&i.AuthorUpdatedAt,
		&i.CatID,
		&i.CatName,
		&i.CatSlug,
		&i.CatDescription,
		&i.CatSortOrder,
		&i.CatCreatedAt,
	)
	return i, err
}

const getThreadOwnership = `-- name: GetThreadOwnership :one
SELECT t.author_id, COALESCE(p.is_admin, false) AS is_admin
FROM threads t LEFT JOIN profiles p ON p.id = $1
WHERE t.id = $2
`

type GetThreadOwnershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ThreadID uuid.UUID `json:"thread_id"`
}

type GetThreadOwnershipRow struct {
	AuthorID uuid.UUID `json:"author_id"`
	IsAdmin  bool      `json:"is_admin"`
}

func (q *Queries) GetThreadOwnership(ctx context.Context, arg GetThreadOwnershipParams) (GetThreadOwnershipRow, error) {
	row := q.db.QueryRow(ctx, getThreadOwnership, arg.UserID, arg.ThreadID)
	var i GetThreadOwnershipRow
	err := row.Scan(&i.AuthorID, &i.IsAdmin)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT t.id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at, t.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM threads t
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
ORDER BY t.is_pinned DESC, t.last_post_at DESC NULLS LAST LIMIT $1
`

type ListThreadsRow struct {
	ID                uuid.UUID `json:"id"`
	CategoryID        uuid.UUID `json:"category_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Title             string    `json:"title"`
	Slug              string    `json:"slug"`
	Content           *string   `json:"content"`
	ImageUrl          *string   `json:"image_url"`
	IsPinned          bool      `json:"is_pinned"`
	IsLocked          bool      `json:"is_locked"`
	ViewCount         int32     `json:"view_count"`
	PostCount         int32     `json:"post_count"`
	LastPostAt        time.Time `json:"last_post_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
	CatID             uuid.UUID `json:"cat_id"`
	CatName           string    `json:"cat_name"`
	CatSlug           string    `json:"cat_slug"`
	CatDescription    *string   `json:"cat_description"`
	CatSortOrder      int32     `json:"cat_sort_order"`
	CatCreatedAt      time.Time `json:"cat_created_at"`
}

func (q *Queries) ListThreads(ctx context.Context, limit int32) ([]ListThreadsRow, error) {
	rows, err := q.db.Query(ctx, listThreads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsRow{}
	for rows.Next() {
		var i ListThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.ViewCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.CatID,
			&i.CatName,
			&i.CatSlug,
			&i.CatDescription,
			&i.CatSortOrder,
			&i.CatCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByCategory = `-- name: ListThreadsByCategory :many
SELECT t.id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at, t.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM threads t
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
WHERE c.slug = $1 ORDER BY t.is_pinned DESC, t.last_post_at DESC NULLS LAST
`

type ListThreadsByCategoryRow struct {
	ID                uuid.UUID `json:"id"`
	CategoryID        uuid.UUID `json:"category_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Title             string    `json:"title"`
	Slug              string    `json:"slug"`
	Content           *string   `json:"content"`
	ImageUrl          *string   `json:"image_url"`
	IsPinned          bool      `json:"is_pinned"`
	IsLocked          bool      `json:"is_locked"`
	ViewCount         int32     `json:"view_count"`
	PostCount         int32     `json:"post_count"`
	LastPostAt        time.Time `json:"last_post_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
	CatID             uuid.UUID `json:"cat_id"`
	CatName           string    `json:"cat_name"`
	CatSlug           string    `json:"cat_slug"`
	CatDescription    *string   `json:"cat_description"`
	CatSortOrder      int32     `json:"cat_sort_order"`
	CatCreatedAt      time.Time `json:"cat_created_at"`
}

func (q *Queries) ListThreadsByCategory(ctx context.Context, slug string) ([]ListThreadsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listThreadsByCategory, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsByCategoryRow{}
	for rows.Next() {
		var i ListThreadsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.ViewCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.CatID,
			&i.CatName,
			&i.CatSlug,
			&i.CatDescription,
			&i.CatSortOrder,
			&i.CatCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserThreads = `-- name: ListUserThreads :many
SELECT t.id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at, t.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM threads t
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
WHERE t.author_id = $1 ORDER BY t.created_at DESC LIMIT 10
`

type ListUserThreadsRow struct {
	ID                uuid.UUID `json:"id"`
	CategoryID        uuid.UUID `json:"category_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Title             string    `json:"title"`
	Slug              string    `json:"slug"`
	Content           *string   `json:"content"`
	ImageUrl          *string   `json:"image_url"`
	IsPinned          bool      `json:"is_pinned"`
	IsLocked          bool      `json:"is_locked"`
	ViewCount         int32     `json:"view_count"`
	PostCount         int32     `json:"post_count"`
	LastPostAt        time.Time `json:"last_post_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
	CatID             uuid.UUID `json:"cat_id"`
	CatName           string    `json:"cat_name"`
	CatSlug           string    `json:"cat_slug"`
	CatDescription    *string   `json:"cat_description"`
	CatSortOrder      int32     `json:"cat_sort_order"`
	CatCreatedAt      time.Time `json:"cat_created_at"`
}

func (q *Queries) ListUserThreads(ctx context.Context, authorID uuid.UUID) ([]ListUserThreadsRow, error) {
	rows, err := q.db.Query(ctx, listUserThreads, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserThreadsRow{}
	for rows.Next() {
		var i ListUserThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.ViewCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.CatID,
			&i.CatName,
			&i.CatSlug,
			&i.CatDescription,
			&i.CatSortOrder,
			&i.CatCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchThreads = `-- name: SearchThreads :many
SELECT t.id, t.category_id, t.author_id, t.title, t.slug, t.content, t.image_url,
       t.is_pinned, t.is_locked, t.view_count, t.post_count,
       COALESCE(t.last_post_at, t.created_at) AS last_post_at, t.created_at, t.updated_at,
       p.id AS author_id_2, p.username AS author_username, p.display_name AS author_display_name,
       p.avatar_url AS author_avatar_url, p.bio AS author_bio, p.website AS author_website,
       p.is_admin AS author_is_admin, p.forumline_id AS author_forumline_id,
       p.created_at AS author_created_at, p.updated_at AS author_updated_at,
       c.id AS cat_id, c.name AS cat_name, c.slug AS cat_slug,
       c.description AS cat_description, c.sort_order AS cat_sort_order, c.created_at AS cat_created_at
FROM threads t
JOIN profiles p ON p.id = t.author_id
JOIN categories c ON c.id = t.category_id
WHERE t.title ILIKE $1 ORDER BY t.created_at DESC LIMIT 20
`

type SearchThreadsRow struct {
	ID                uuid.UUID `json:"id"`
	CategoryID        uuid.UUID `json:"category_id"`
	AuthorID          uuid.UUID `json:"author_id"`
	Title             string    `json:"title"`
	Slug              string    `json:"slug"`
	Content           *string   `json:"content"`
	ImageUrl          *string   `json:"image_url"`
	IsPinned          bool      `json:"is_pinned"`
	IsLocked          bool      `json:"is_locked"`
	ViewCount         int32     `json:"view_count"`
	PostCount         int32     `json:"post_count"`
	LastPostAt        time.Time `json:"last_post_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	AuthorID2         uuid.UUID `json:"author_id_2"`
	AuthorUsername    string    `json:"author_username"`
	AuthorDisplayName *string   `json:"author_display_name"`
	AuthorAvatarUrl   *string   `json:"author_avatar_url"`
	AuthorBio         *string   `json:"author_bio"`
	AuthorWebsite     *string   `json:"author_website"`
	AuthorIsAdmin     bool      `json:"author_is_admin"`
	AuthorForumlineID *string   `json:"author_forumline_id"`
	AuthorCreatedAt   time.Time `json:"author_created_at"`
	AuthorUpdatedAt   time.Time `json:"author_updated_at"`
	CatID             uuid.UUID `json:"cat_id"`
	CatName           string    `json:"cat_name"`
	CatSlug           string    `json:"cat_slug"`
	CatDescription    *string   `json:"cat_description"`
	CatSortOrder      int32     `json:"cat_sort_order"`
	CatCreatedAt      time.Time `json:"cat_created_at"`
}

func (q *Queries) SearchThreads(ctx context.Context, title string) ([]SearchThreadsRow, error) {
	rows, err := q.db.Query(ctx, searchThreads, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchThreadsRow{}
	for rows.Next() {
		var i SearchThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.ViewCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID2,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorBio,
			&i.AuthorWebsite,
			&i.AuthorIsAdmin,
			&i.AuthorForumlineID,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.CatID,
			&i.CatName,
			&i.CatSlug,
			&i.CatDescription,
			&i.CatSortOrder,
			&i.CatCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadStats = `-- name: UpdateThreadStats :exec
UPDATE threads SET last_post_at = $2, post_count = post_count + 1, updated_at = $2 WHERE id = $1
`

type UpdateThreadStatsParams struct {
	ID         uuid.UUID  `json:"id"`
	LastPostAt *time.Time `json:"last_post_at"`
}

func (q *Queries) UpdateThreadStats(ctx context.Context, arg UpdateThreadStatsParams) error {
	_, err := q.db.Exec(ctx, updateThreadStats, arg.ID, arg.LastPostAt)
	return err
}
