// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearVoicePresence = `-- name: ClearVoicePresence :exec
DELETE FROM voice_presence WHERE user_id = $1
`

func (q *Queries) ClearVoicePresence(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearVoicePresence, userID)
	return err
}

const listVoicePresence = `-- name: ListVoicePresence :many
SELECT vp.id, vp.user_id, vp.room_slug, vp.joined_at,
       p.id AS profile_id, p.username AS profile_username, p.display_name AS profile_display_name,
       p.avatar_url AS profile_avatar_url, p.bio AS profile_bio, p.website AS profile_website,
       p.is_admin AS profile_is_admin, p.forumline_id AS profile_forumline_id,
       p.created_at AS profile_created_at, p.updated_at AS profile_updated_at
FROM voice_presence vp
JOIN profiles p ON p.id = vp.user_id
`

type ListVoicePresenceRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	RoomSlug           string             `json:"room_slug"`
	JoinedAt           pgtype.Timestamptz `json:"joined_at"`
	ProfileID          uuid.UUID          `json:"profile_id"`
	ProfileUsername    string             `json:"profile_username"`
	ProfileDisplayName pgtype.Text        `json:"profile_display_name"`
	ProfileAvatarUrl   pgtype.Text        `json:"profile_avatar_url"`
	ProfileBio         pgtype.Text        `json:"profile_bio"`
	ProfileWebsite     pgtype.Text        `json:"profile_website"`
	ProfileIsAdmin     bool               `json:"profile_is_admin"`
	ProfileForumlineID pgtype.Text        `json:"profile_forumline_id"`
	ProfileCreatedAt   pgtype.Timestamptz `json:"profile_created_at"`
	ProfileUpdatedAt   pgtype.Timestamptz `json:"profile_updated_at"`
}

func (q *Queries) ListVoicePresence(ctx context.Context) ([]ListVoicePresenceRow, error) {
	rows, err := q.db.Query(ctx, listVoicePresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoicePresenceRow{}
	for rows.Next() {
		var i ListVoicePresenceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomSlug,
			&i.JoinedAt,
			&i.ProfileID,
			&i.ProfileUsername,
			&i.ProfileDisplayName,
			&i.ProfileAvatarUrl,
			&i.ProfileBio,
			&i.ProfileWebsite,
			&i.ProfileIsAdmin,
			&i.ProfileForumlineID,
			&i.ProfileCreatedAt,
			&i.ProfileUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceRooms = `-- name: ListVoiceRooms :many
SELECT id, name, slug, created_at
FROM voice_rooms ORDER BY name
`

func (q *Queries) ListVoiceRooms(ctx context.Context) ([]VoiceRoom, error) {
	rows, err := q.db.Query(ctx, listVoiceRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceRoom{}
	for rows.Next() {
		var i VoiceRoom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVoicePresence = `-- name: SetVoicePresence :exec
INSERT INTO voice_presence (user_id, room_slug, joined_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET room_slug = $2, joined_at = $3
`

type SetVoicePresenceParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	RoomSlug string             `json:"room_slug"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) SetVoicePresence(ctx context.Context, arg SetVoicePresenceParams) error {
	_, err := q.db.Exec(ctx, setVoicePresence, arg.UserID, arg.RoomSlug, arg.JoinedAt)
	return err
}
