// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: call.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateCall = `-- name: ActivateCall :exec
UPDATE forumline_calls SET status = 'active', started_at = now() WHERE id = $1
`

func (q *Queries) ActivateCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateCall, id)
	return err
}

const createCallRecord = `-- name: CreateCallRecord :one
INSERT INTO forumline_calls (conversation_id, caller_id, callee_id, status, room_name)
VALUES ($1, $2, $3, 'ringing', $4)
RETURNING id, conversation_id, caller_id, callee_id, status, room_name, created_at
`

type CreateCallRecordParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	CallerID       string    `json:"caller_id"`
	CalleeID       string    `json:"callee_id"`
	RoomName       *string   `json:"room_name"`
}

type CreateCallRecordRow struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	CallerID       string    `json:"caller_id"`
	CalleeID       string    `json:"callee_id"`
	Status         string    `json:"status"`
	RoomName       *string   `json:"room_name"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateCallRecord(ctx context.Context, arg CreateCallRecordParams) (CreateCallRecordRow, error) {
	row := q.db.QueryRow(ctx, createCallRecord,
		arg.ConversationID,
		arg.CallerID,
		arg.CalleeID,
		arg.RoomName,
	)
	var i CreateCallRecordRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.RoomName,
		&i.CreatedAt,
	)
	return i, err
}

const endCallWithDuration = `-- name: EndCallWithDuration :exec
UPDATE forumline_calls SET status = $1, ended_at = now(), duration_seconds = $2 WHERE id = $3
`

type EndCallWithDurationParams struct {
	Status          string      `json:"status"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) EndCallWithDuration(ctx context.Context, arg EndCallWithDurationParams) error {
	_, err := q.db.Exec(ctx, endCallWithDuration, arg.Status, arg.DurationSeconds, arg.ID)
	return err
}

const endCallWithoutDuration = `-- name: EndCallWithoutDuration :exec
UPDATE forumline_calls SET status = $1, ended_at = now() WHERE id = $2
`

type EndCallWithoutDurationParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) EndCallWithoutDuration(ctx context.Context, arg EndCallWithoutDurationParams) error {
	_, err := q.db.Exec(ctx, endCallWithoutDuration, arg.Status, arg.ID)
	return err
}

const getCallByID = `-- name: GetCallByID :one
SELECT id, conversation_id, caller_id, callee_id, status, room_name, created_at, started_at, ended_at, duration_seconds
FROM forumline_calls WHERE id = $1
`

type GetCallByIDRow struct {
	ID              uuid.UUID   `json:"id"`
	ConversationID  uuid.UUID   `json:"conversation_id"`
	CallerID        string      `json:"caller_id"`
	CalleeID        string      `json:"callee_id"`
	Status          string      `json:"status"`
	RoomName        *string     `json:"room_name"`
	CreatedAt       time.Time   `json:"created_at"`
	StartedAt       *time.Time  `json:"started_at"`
	EndedAt         *time.Time  `json:"ended_at"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) GetCallByID(ctx context.Context, id uuid.UUID) (GetCallByIDRow, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i GetCallByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.RoomName,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
	)
	return i, err
}

const getCallByRoomName = `-- name: GetCallByRoomName :one
SELECT id, conversation_id, caller_id, callee_id, status, room_name, created_at, started_at, ended_at, duration_seconds
FROM forumline_calls WHERE room_name = $1 AND status IN ('ringing', 'active')
`

type GetCallByRoomNameRow struct {
	ID              uuid.UUID   `json:"id"`
	ConversationID  uuid.UUID   `json:"conversation_id"`
	CallerID        string      `json:"caller_id"`
	CalleeID        string      `json:"callee_id"`
	Status          string      `json:"status"`
	RoomName        *string     `json:"room_name"`
	CreatedAt       time.Time   `json:"created_at"`
	StartedAt       *time.Time  `json:"started_at"`
	EndedAt         *time.Time  `json:"ended_at"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) GetCallByRoomName(ctx context.Context, roomName *string) (GetCallByRoomNameRow, error) {
	row := q.db.QueryRow(ctx, getCallByRoomName, roomName)
	var i GetCallByRoomNameRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.RoomName,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
	)
	return i, err
}

const getCalleeFor1to1 = `-- name: GetCalleeFor1to1 :one
SELECT cm2.user_id FROM forumline_conversations c
JOIN forumline_conversation_members cm1 ON cm1.conversation_id = c.id AND cm1.user_id = $1
JOIN forumline_conversation_members cm2 ON cm2.conversation_id = c.id AND cm2.user_id != $1
WHERE c.id = $2 AND c.is_group = false
AND (SELECT count(*) FROM forumline_conversation_members WHERE conversation_id = c.id) = 2
`

type GetCalleeFor1to1Params struct {
	UserID         string    `json:"user_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

func (q *Queries) GetCalleeFor1to1(ctx context.Context, arg GetCalleeFor1to1Params) (string, error) {
	row := q.db.QueryRow(ctx, getCalleeFor1to1, arg.UserID, arg.ConversationID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const isCallParticipant = `-- name: IsCallParticipant :one
SELECT EXISTS(SELECT 1 FROM forumline_calls
WHERE id = $1 AND (caller_id = $2 OR callee_id = $2))
`

type IsCallParticipantParams struct {
	ID       uuid.UUID `json:"id"`
	CallerID string    `json:"caller_id"`
}

func (q *Queries) IsCallParticipant(ctx context.Context, arg IsCallParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCallParticipant, arg.ID, arg.CallerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCallStatus = `-- name: UpdateCallStatus :exec
UPDATE forumline_calls SET status = $1 WHERE id = $2
`

type UpdateCallStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) error {
	_, err := q.db.Exec(ctx, updateCallStatus, arg.Status, arg.ID)
	return err
}
