//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JWK A single JSON Web Key per RFC 7517.
type JWK struct {
	// Alg Algorithm (e.g. RS256).
	Alg *string `json:"alg,omitempty"`

	// E RSA exponent (base64url-encoded).
	E *string `json:"e,omitempty"`

	// Kid Key ID.
	Kid string `json:"kid"`

	// Kty Key type (e.g. RSA, EC).
	Kty string `json:"kty"`

	// N RSA modulus (base64url-encoded).
	N *string `json:"n,omitempty"`

	// Use Key usage (sig for signing).
	Use string `json:"use"`
}

// JWKS JSON Web Key Set per RFC 7517.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// Code The single-use auth code received from the callback redirect.
	Code string `json:"code"`

	// RedirectUri Must exactly match the redirect_uri used in the original /authorize request.
	RedirectUri string `json:"redirect_uri"`
}

// UserInfo Full user identity payload returned from the token exchange. Includes
// the Zitadel access token so forums can make further API calls on behalf
// of the user.
type UserInfo struct {
	// AccessToken Zitadel access token for making API calls on behalf of the user.
	AccessToken string `json:"access_token"`

	// AvatarUrl URL to the user's profile picture. May be empty if none is set.
	AvatarUrl string `json:"avatar_url"`

	// DisplayName User's display name (given + family name), falling back to username.
	DisplayName string `json:"display_name"`

	// ForumlineId Stable user identifier (Zitadel subject ID).
	ForumlineId string `json:"forumline_id"`

	// Username User's preferred username, falling back to email.
	Username string `json:"username"`
}

// UserInfoPublic User identity payload returned from the /userinfo endpoint. Does not
// include the access token (the caller already has it).
type UserInfoPublic struct {
	// AvatarUrl URL to the user's profile picture. May be empty if none is set.
	AvatarUrl string `json:"avatar_url"`

	// DisplayName User's display name, falling back to username.
	DisplayName string `json:"display_name"`

	// ForumlineId Stable user identifier (Zitadel subject ID).
	ForumlineId string `json:"forumline_id"`

	// Username User's preferred username, falling back to email.
	Username string `json:"username"`
}

// AuthorizeParams defines parameters for Authorize.
type AuthorizeParams struct {
	// RedirectUri The forum's callback URL where the user will be redirected after login.
	// Must be on a `*.forumline.net` domain or localhost.
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`

	// State Opaque CSRF state value from the forum. Returned unmodified in the callback redirect.
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// CallbackParams defines parameters for Callback.
type CallbackParams struct {
	// Code Zitadel OIDC authorization code.
	Code string `form:"code" json:"code"`

	// State OIDC state value, must match the `forumline_id_state` cookie.
	State string `form:"state" json:"state"`
}

// UserInfoParams defines parameters for UserInfo.
type UserInfoParams struct {
	// AccessToken Alternative to the Authorization header. Provide the access token as a query parameter.
	AccessToken *string `form:"access_token,omitempty" json:"access_token,omitempty"`
}

// TokenExchangeJSONRequestBody defines body for TokenExchange for application/json ContentType.
type TokenExchangeJSONRequestBody = TokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks)
	Jwks(w http.ResponseWriter, r *http.Request)
	// Start the "Sign in with Forumline" flow
	// (GET /authorize)
	Authorize(w http.ResponseWriter, r *http.Request, params AuthorizeParams)
	// Zitadel OIDC callback
	// (GET /callback)
	Callback(w http.ResponseWriter, r *http.Request, params CallbackParams)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Exchange auth code for user info
	// (POST /token)
	TokenExchange(w http.ResponseWriter, r *http.Request)
	// Validate JWT and return user profile
	// (GET /userinfo)
	UserInfo(w http.ResponseWriter, r *http.Request, params UserInfoParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Jwks operation middleware
func (siw *ServerInterfaceWrapper) Jwks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Jwks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Authorize operation middleware
func (siw *ServerInterfaceWrapper) Authorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizeParams

	// ------------- Required query parameter "redirect_uri" -------------

	if paramValue := r.URL.Query().Get("redirect_uri"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectUri, runtime.BindQueryParameterOptions{Type: "string", Format: "uri"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Authorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Callback operation middleware
func (siw *ServerInterfaceWrapper) Callback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Callback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TokenExchange operation middleware
func (siw *ServerInterfaceWrapper) TokenExchange(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TokenExchange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserInfo operation middleware
func (siw *ServerInterfaceWrapper) UserInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UserInfoParams

	// ------------- Optional query parameter "access_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "access_token", r.URL.Query(), &params.AccessToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "access_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserInfo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/.well-known/jwks", wrapper.Jwks)
	m.HandleFunc("GET "+options.BaseURL+"/authorize", wrapper.Authorize)
	m.HandleFunc("GET "+options.BaseURL+"/callback", wrapper.Callback)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)
	m.HandleFunc("POST "+options.BaseURL+"/token", wrapper.TokenExchange)
	m.HandleFunc("GET "+options.BaseURL+"/userinfo", wrapper.UserInfo)

	return m
}

type JwksRequestObject struct {
}

type JwksResponseObject interface {
	VisitJwksResponse(w http.ResponseWriter) error
}

type Jwks200ResponseHeaders struct {
	CacheControl string
}

type Jwks200JSONResponse struct {
	Body    JWKS
	Headers Jwks200ResponseHeaders
}

func (response Jwks200JSONResponse) VisitJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Jwks502JSONResponse ErrorResponse

func (response Jwks502JSONResponse) VisitJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizeRequestObject struct {
	Params AuthorizeParams
}

type AuthorizeResponseObject interface {
	VisitAuthorizeResponse(w http.ResponseWriter) error
}

type Authorize302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type Authorize302Response struct {
	Headers Authorize302ResponseHeaders
}

func (response Authorize302Response) VisitAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type Authorize400JSONResponse ErrorResponse

func (response Authorize400JSONResponse) VisitAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CallbackRequestObject struct {
	Params CallbackParams
}

type CallbackResponseObject interface {
	VisitCallbackResponse(w http.ResponseWriter) error
}

type Callback302ResponseHeaders struct {
	Location string
}

type Callback302Response struct {
	Headers Callback302ResponseHeaders
}

func (response Callback302Response) VisitCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Callback400JSONResponse ErrorResponse

func (response Callback400JSONResponse) VisitCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Callback500JSONResponse ErrorResponse

func (response Callback500JSONResponse) VisitCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TokenExchangeRequestObject struct {
	Body *TokenExchangeJSONRequestBody
}

type TokenExchangeResponseObject interface {
	VisitTokenExchangeResponse(w http.ResponseWriter) error
}

type TokenExchange200JSONResponse UserInfo

func (response TokenExchange200JSONResponse) VisitTokenExchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TokenExchange400JSONResponse ErrorResponse

func (response TokenExchange400JSONResponse) VisitTokenExchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TokenExchange401JSONResponse ErrorResponse

func (response TokenExchange401JSONResponse) VisitTokenExchangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UserInfoRequestObject struct {
	Params UserInfoParams
}

type UserInfoResponseObject interface {
	VisitUserInfoResponse(w http.ResponseWriter) error
}

type UserInfo200JSONResponse UserInfoPublic

func (response UserInfo200JSONResponse) VisitUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UserInfo401JSONResponse ErrorResponse

func (response UserInfo401JSONResponse) VisitUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UserInfo502JSONResponse ErrorResponse

func (response UserInfo502JSONResponse) VisitUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks)
	Jwks(ctx context.Context, request JwksRequestObject) (JwksResponseObject, error)
	// Start the "Sign in with Forumline" flow
	// (GET /authorize)
	Authorize(ctx context.Context, request AuthorizeRequestObject) (AuthorizeResponseObject, error)
	// Zitadel OIDC callback
	// (GET /callback)
	Callback(ctx context.Context, request CallbackRequestObject) (CallbackResponseObject, error)
	// Health check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Exchange auth code for user info
	// (POST /token)
	TokenExchange(ctx context.Context, request TokenExchangeRequestObject) (TokenExchangeResponseObject, error)
	// Validate JWT and return user profile
	// (GET /userinfo)
	UserInfo(ctx context.Context, request UserInfoRequestObject) (UserInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Jwks operation middleware
func (sh *strictHandler) Jwks(w http.ResponseWriter, r *http.Request) {
	var request JwksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Jwks(ctx, request.(JwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Jwks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JwksResponseObject); ok {
		if err := validResponse.VisitJwksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Authorize operation middleware
func (sh *strictHandler) Authorize(w http.ResponseWriter, r *http.Request, params AuthorizeParams) {
	var request AuthorizeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Authorize(ctx, request.(AuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Authorize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthorizeResponseObject); ok {
		if err := validResponse.VisitAuthorizeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Callback operation middleware
func (sh *strictHandler) Callback(w http.ResponseWriter, r *http.Request, params CallbackParams) {
	var request CallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Callback(ctx, request.(CallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Callback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CallbackResponseObject); ok {
		if err := validResponse.VisitCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TokenExchange operation middleware
func (sh *strictHandler) TokenExchange(w http.ResponseWriter, r *http.Request) {
	var request TokenExchangeRequestObject

	var body TokenExchangeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TokenExchange(ctx, request.(TokenExchangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TokenExchange")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TokenExchangeResponseObject); ok {
		if err := validResponse.VisitTokenExchangeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserInfo operation middleware
func (sh *strictHandler) UserInfo(w http.ResponseWriter, r *http.Request, params UserInfoParams) {
	var request UserInfoRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserInfo(ctx, request.(UserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserInfoResponseObject); ok {
		if err := validResponse.VisitUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOJD+KwPdAXVubTlvTbEBFods2lzTba+5ON0CVxcxLY0tNhSpJSkn3kX++2FI",
	"vVqy0xYtDjjclzaWKHJmOPM8M0P+E0QqzZREaU1w+k9gogRT5v58pbXS12gyJQ3Sg0yrDLXl6F4jvaY/",
	"YjSR5pnlSganwes8ZXKkkcVsLhDcKEjRGLbEMBgG+MDSTGBwGnC5YoLHoPGvHI2FuYrXwTCw64zeGqu5",
	"XAaPj8OABnCNcXD6qVj1czVMzb9gZIPHYfAambDJdnmNZTb3kss8pbnUHU1UC6Tunly+mKRv/Tcf/+ha",
	"4wwMl0uB8Gby/j/hI87hD1xDhhquL87hxfODF2STtqBMLHsmEkuluU1SGGC4DOF6cvj8ZK9tUPesq8Iw",
	"wO5815MzwAe/8TCYM4Mnx7kWI5SRijHemPnsv85+75v4jsfdqUnDy5dh73i77h9PIyvNzobw6ryj21nf",
	"hLJfs1TFucjNNsU60+QG++XKyW1hYPgSFkqD4UvJ5XJDNsOXTzoOae7X8Vbb4kGTrhgtz5mgfcJ77nDt",
	"/ucWU/fHv2pcBKfBv4zrQB8XUT4mn32sJGFas3VXcpqwT9wbdYfy2gdvN9zI2l1lbhIsImKUGwSW2wRo",
	"JGiMkK8whoVWKdgEIWJCzFl0BxpjrjGybaOzg/lhdBQf4/PFSRj27mr54W2ueVeUd7mxgA8ssmINKbNR",
	"4pZtfgS5wRi4dC+U5ksumYAxSa00/xtL6GpLllibmdPx2KKxC6XzNHT/Ci4xlGjHLOPj6ombbFzqGgyD",
	"hdIps8FpQEI/5VXOyBuK9m3VB4P6Ui5U1woXuRCkpgYeo7TcriFja6EY4bLNtWxuiaUdB3yIEiaXGMKl",
	"jEQeo5lKevvf3LIYBbAoQmOKwUaB09VAxCSk7A5hkWuboIazq0u3yQaUhDkmTCymUi3cSiRROJVdbHRz",
	"37q5u8r0SkBxm7I7Lpd9K0JzwT4nYitmmb7Nteiu9+H6LVhVff/MQKbVgguEjEc21xjCO7aGOQKmmV0D",
	"X4BUEoEbMLjFa8gfNh3GGLRmvDoYb3H0mJtMsPWtZGlPzH3wohWDgAbBYMlXKOEXWLCUC/9wbwgLJgQZ",
	"ysWdVU4retUW9Y1KJPypZKyZSfCuT6JKgds+hphYlxs03G7BUcOg3D+TO8+Fy5cbSHt0cnx8cHD068mL",
	"k/2Dw6Pjfrorpd5qikzjArXGuFKwqzqmjIv26l9UIlc71N4IzpYNGlJt7FfLxYZtD98Vy1f5XPCoX8ev",
	"CeYxCcTlQgHKOFNc2hBeKjQglZ1K7kPbjWyF06DEZtTABOV5a0iYAW73egP2/2L4/H+g/K8HSjcyHoeB",
	"wSjX3K4nlN54/5sj06jPcpvUvy5Kin3z8YYWaRNiKUxl5b1WAJCmLn2itf18tYLkhcEjicILto2UtCxy",
	"+ZG3dL0AqUphUfluy22dY7YkmwYTvpSUjtxzm0A1zzSA96QgRc/DGgzqFY8QdC4pVwVmgcftkAincipv",
	"Em5A8GVi75H+rTGjnOFes8xUtG4oUpkt6XyQKGMxBibjqTQoFiP/YA8krlCDZcK5R/m5z1DEOoRLS35l",
	"KBEFBoaT03gNRsauBU5lmWAx0tznhwuh7k9J7IPQa14lasaHh1Uw+49XN43sbDaVhyE4OKRnpFzELBpv",
	"vlKugdVMmoxpKoQaaLQ3lUchnG8moabye2cHPxeTdSY7lcelhGWiZHw+S2qQaVGPrBr5v2DFGcyu3k9u",
	"YOzca0Y6XigNXI5YlsGALzRxc1MFruSwmVUxYRS4WppZBFZ7Brz5eDOVpeX9Ws5GJfTPhrR/sEDKfovi",
	"Bijh9zThB4f3KMToTqp7Of5yf2dmHucFj7AotAvPvtIq0xwt0+unfdtyK1rhAJel/028/wXDYIXaeOc/",
	"CPfDffpOZShZxgnjwv3wiAiH2cTFekdSerhE24W3K60eOFa+/cwA1V4VEW5krZVpW4Y1U0mbr3ILtCJZ",
	"rvQpfODGmhDKZgQxVsSihOhXaXgOKZe5ReMNSXTpNvUyJkwiuQkf/adOh8P9/RJLUDp1WJaJwhXGX4yS",
	"devmK0q+iYeojTKTDBCrKE8pEBxscecO5LuZyzVaHkI4mCCLUTsRz0m90bmSVqseqqfX9KX3Rb7C0JWy",
	"FLR+7iGk7GHElvjb0f7+DAaVjfYqwHWq1STT810P05Ciz/cPv8J8xcxOm1xqZFFC5Es/V0zk2Oh5BXV6",
	"pdWKx6ih+QWt6X7HWydYMC4wJv1pGNSb8nWb2G7N9exm6Yltt+amKScoXaeFTEItMpTeF7ZoNTj99HkY",
	"mDxNKcK7nQkyP1saovSX3ERqhXodfKYZalDeGpIXPt5KnHUYbCBBTWUnzHHJ5QYGhuC6CQVZlUFaFKOz",
	"Zk08G4KxShdA7IHbecODJTplEl7f3FyNlBRriJS64zj0vFajfkkLTUqjWBZqyaXj0zMh1D3GtQYfri/N",
	"Kcz+rc29syHMOg+Eipgg/pwNp5IQeXZw+IIQLzyYwSDGFQqVUWDu9UHGWWVcAkOiC+ui8lNf98Wt/czU",
	"7RXKwu+9nUsd77kQlHaXqpB/LCzW2rreyRypjGZdDSFWKeMSnHkKxbzcnKT4K0dHEAVrtJoXzcTQ6hz7",
	"Q//ndlg2rfY+Y3/lCOeT6wswlnjAhXNdSXkR4LqMpVymKqZMveod9fay+ozh5m8B3qZ4nze44ciD20YP",
	"tPTBDW/dCKA2hL9V/vH2vsr7y5fn0E7OPly/bQP0k/2rCdrRuQuynnoHrWmExy2PbyP7MIPBopXyud7c",
	"L34z9nyktj9yb2YwcAKXwwy8tjZ7L8V6CBOCNBzChKU44RZ/e8septLHfpEgMjjYH3kSgpubt96Bt+8L",
	"qXb8VTzdJJqYG+Zxo5cmWgqnRdAx2Ai4It4CX3c4IOxnrerApRFx9FHKjSEtnhSBG6ji80fS1TsvALi8",
	"1wu5CeCOrGpkBamsgx9Kfz3weivspqyJZdq6kNxRTVGt0eAyX1xd0ENPZhWWbOOya9/MNq2GsseLqkXp",
	"8LRC3FaBEsKfbTKr3Xi4UVRU0/VUTEr7itUMpxIfrGZVrVSlLxWEXb70Y4ewREncgq42S5S2I+H68oOT",
	"fbM3lX3Ne19EdCsku5VuuE2mcvbv9PFv03x//yiiyW5d/UQ/3b+HJ07lYoCbyAe2HzKrq9hmgkN+4dpT",
	"cVVywnxdpvOjEXA3rDJrKfZUkldpXHJjUWPcqhL7WPe8ZpSdpLsDPEnfbUxQtfa30eHTvFV5jSesoUeQ",
	"+qijFzM9Bj7FT18v1jfz1U6vAScP1AY/ncoRzMhYM9rcpsfW1Vp9zDRI8GEIJ8cQJUwbiqaMU17IJXj/",
	"HsGsMMRo1D728RTUTAAGfFEWADHEOSncaD/sOZ/5Kn717YKusoVeLiEspNrU/5vI9/s4qkDkc58w72SW",
	"VmrdpJZdHxdDej52Or/jxrls77d+O9JyyI/kpElr6iH0ilmVCw3mag0IA1eAfoPNm+q18zXwVWPw48tE",
	"FxslsxTL7CbSFqo1kuutpJm46xk7KJOS50ZD0N+0AN/ddW28mHA8zyxPEVIluVXauNhwBxxzJpiMioho",
	"I7W/GXKeoJPwp3VWNi6g9LlUUatyKmxp8Hq3kf2MEBWSbyuuq9PQTBnbl1Rv9Bzr854zl4X4s3fXK+4F",
	"zRVnBIVT2Sljho2Cml6gjIsDVtviZatq7/IzlRlKOx/h0iMYFSeupi5lMMB0++aAjAvwLlKpk30wGCkZ",
	"G98XaOePU5n2H/crif6Uv8Bvx4uNHnJ1xA+Xi4bo3JThXnJI7DCgc4MgVmjks4J1h3UjmJup5GmKMWcW",
	"xbqcjVGtPShveJy8OP6VtHLBfxwehIe99b+7iPGqsG9Bzmjs7ype/zDnbl32eGyf4FAK8PgTA6u6vdAT",
	"Uu3TzqqdZXJ3ZLPIhVg7CP5u2iutuKOaalxfa1DeBUcRm95PnQc0c2bnKuThP6W6uuyRlJy1ZLRyUVg4",
	"kQt7HXwfZZVmUboMDOfwP5C0KlDYGoXtsrlg8N1QW4ZPA/ZqeCLf20Ft5WnKVnKryrkWwPafLxLJuYM8",
	"2hne7OA8M1PZObN3kCILx6f5JQGo4H8XZ7blkXrNoL4SmspFAVe7D5pcMVz0Bxm8+XhDRs+YoclWnE0l",
	"cc674nqnL8jKe0IRkzDHOkNmJN7v7sS0GFF0x85aRZHPmKdSafeFhFnzSkQnA+4DxAownijNzoRFLZnl",
	"Kywrjz5ZQrjyOnRvQzidNiXaUju1bnZ8S8n0M7C0uD3SE143fmuM76iXbU2z1bG+GS2a6LoTWRsQ4o32",
	"VK+qBLR5w8l+Rp9qWMPOpoxFvn/4neC5+1zph+f9HTjZOCLqYGb7QsWnz48tEC1xzuGE5zfynZa/NIDU",
	"e1rxEQn22e+Vy1L74vVKqzh32VDnfHnzikNAkhUL/dNDID3XCyojGJ8R1l0jq1oNOn82FdaR3WCEbhvm",
	"VTUrIW6R5ZGXvvl4Y0oraY4uAe9pzzWdublox3rdpT9Wx+EN3UiKO1xDXFYRTobyGM3XJY1l6mLj8fPj",
	"/wQAAP//+OqybS4wAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
