//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ForumlineIdentityScopes = "forumlineIdentity.Scopes"
)

// Defines values for ResetResponseStatus.
const (
	ResetComplete ResetResponseStatus = "reset complete"
)

// Valid indicates whether the value is a known member of the ResetResponseStatus enum.
func (e ResetResponseStatus) Valid() bool {
	switch e {
	case ResetComplete:
		return true
	default:
		return false
	}
}

// DeleteFileResponse defines model for DeleteFileResponse.
type DeleteFileResponse struct {
	// Deleted Path of the deleted file.
	Deleted string `json:"deleted"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// ExportData defines model for ExportData.
type ExportData struct {
	// Bookmarks Bookmark rows as JSON objects.
	Bookmarks []map[string]interface{} `json:"bookmarks"`

	// Categories Category rows as JSON objects.
	Categories []map[string]interface{} `json:"categories"`

	// ChannelFollows Channel follow rows as JSON objects.
	ChannelFollows []map[string]interface{} `json:"channel_follows"`

	// ChatChannels Chat channel rows as JSON objects.
	ChatChannels []map[string]interface{} `json:"chat_channels"`

	// ChatMessages Chat message rows as JSON objects.
	ChatMessages []map[string]interface{} `json:"chat_messages"`

	// ExportedAt UTC timestamp of when the export was created.
	ExportedAt time.Time `json:"exported_at"`
	Forum      ForumMeta `json:"forum"`

	// ForumlineVersion Export format version.
	ForumlineVersion string `json:"forumline_version"`

	// NotificationPreferences Notification preference rows as JSON objects.
	NotificationPreferences []map[string]interface{} `json:"notification_preferences"`

	// Notifications Notification rows as JSON objects.
	Notifications []map[string]interface{} `json:"notifications"`

	// Posts Post rows as JSON objects.
	Posts []map[string]interface{} `json:"posts"`

	// Profiles Profile rows as JSON objects.
	Profiles []map[string]interface{} `json:"profiles"`

	// Threads Thread rows as JSON objects.
	Threads []map[string]interface{} `json:"threads"`

	// VoiceRooms Voice room rows as JSON objects.
	VoiceRooms []map[string]interface{} `json:"voice_rooms"`
}

// FileManifestResponse defines model for FileManifestResponse.
type FileManifestResponse struct {
	// Files Map of file path to file metadata. Keys are relative paths like
	// `index.html` or `css/style.css`.
	Files map[string]SiteFileEntry `json:"files"`

	// StorageBytes Total bytes used by the custom site.
	StorageBytes int64 `json:"storage_bytes"`

	// StorageLimit Storage quota in bytes.
	StorageLimit int64 `json:"storage_limit"`

	// Updated UTC timestamp of the last manifest update.
	Updated time.Time `json:"updated"`
}

// ForumMeta defines model for ForumMeta.
type ForumMeta struct {
	Description string `json:"description"`
	Domain      string `json:"domain"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// ForumSummary defines model for ForumSummary.
type ForumSummary struct {
	// Description Forum description (may be empty string).
	Description string `json:"description"`

	// Domain Full domain.
	Domain string `json:"domain"`

	// IconUrl URL to the forum icon (may be empty string).
	IconUrl string `json:"icon_url"`

	// Name Forum display name.
	Name string `json:"name"`

	// Slug Forum slug (subdomain).
	Slug string `json:"slug"`

	// Theme Forum theme identifier.
	Theme string `json:"theme"`
}

// MultipartUploadResponse defines model for MultipartUploadResponse.
type MultipartUploadResponse struct {
	// Errors Per-file error messages for files that failed. Each string has the
	// format `filename: reason`.
	Errors []string `json:"errors"`

	// Uploaded File paths that were successfully uploaded.
	Uploaded []string `json:"uploaded"`
}

// OwnedSite defines model for OwnedSite.
type OwnedSite struct {
	// Domain Full domain of the forum.
	Domain string `json:"domain"`

	// Slug Forum slug.
	Slug string `json:"slug"`
}

// ProvisionRequest defines model for ProvisionRequest.
type ProvisionRequest struct {
	// Description Optional forum description.
	Description *string `json:"description,omitempty"`

	// Name Display name for the forum.
	Name string `json:"name"`

	// Slug Subdomain for the forum. Becomes `{slug}.forumline.net`. Lowercase
	// alphanumeric and hyphens, 1-40 characters, cannot start/end with hyphen.
	Slug string `json:"slug"`
}

// ProvisionResponse defines model for ProvisionResponse.
type ProvisionResponse struct {
	// Domain Full domain of the new forum.
	Domain string `json:"domain"`

	// Name Forum display name.
	Name string `json:"name"`

	// SchemaName PostgreSQL schema name for the forum's data.
	SchemaName string `json:"schema_name"`

	// Slug Forum slug.
	Slug string `json:"slug"`
}

// PutFileResponse defines model for PutFileResponse.
type PutFileResponse struct {
	// Etag MD5 hex digest of the uploaded content.
	Etag string `json:"etag"`

	// Path Sanitized file path that was written.
	Path string `json:"path"`

	// Size File size in bytes (as a string).
	Size string `json:"size"`
}

// ResetResponse defines model for ResetResponse.
type ResetResponse struct {
	// Status Always `"reset complete"` on success.
	Status ResetResponseStatus `json:"status"`
}

// ResetResponseStatus Always `"reset complete"` on success.
type ResetResponseStatus string

// SiteFileEntry defines model for SiteFileEntry.
type SiteFileEntry struct {
	// ContentType MIME type of the file.
	ContentType string `json:"content_type"`

	// Etag MD5 hex digest of the file content.
	Etag string `json:"etag"`

	// Size File size in bytes.
	Size int64 `json:"size"`

	// Updated UTC timestamp of last upload.
	Updated time.Time `json:"updated"`
}

// FilePath defines model for filePath.
type FilePath = string

// Slug defines model for slug.
type Slug = string

// MultipartUploadMultipartBody defines parameters for MultipartUpload.
type MultipartUploadMultipartBody struct {
	// Files One or more files to upload. Filenames are used as file paths.
	Files *[]openapi_types.File `json:"files,omitempty"`
}

// ProvisionForumJSONRequestBody defines body for ProvisionForum for application/json ContentType.
type ProvisionForumJSONRequestBody = ProvisionRequest

// MultipartUploadMultipartRequestBody defines body for MultipartUpload for multipart/form-data ContentType.
type MultipartUploadMultipartRequestBody MultipartUploadMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all active hosted forums
	// (GET /api/platform/forums)
	ListForums(w http.ResponseWriter, r *http.Request)
	// Provision a new hosted forum
	// (POST /api/platform/forums)
	ProvisionForum(w http.ResponseWriter, r *http.Request)
	// Export forum data as JSON
	// (GET /api/platform/forums/{slug}/export)
	ExportForum(w http.ResponseWriter, r *http.Request, slug Slug)
	// List forums owned by the caller
	// (GET /api/platform/owned-sites)
	ListOwnedSites(w http.ResponseWriter, r *http.Request)
	// List custom site files
	// (GET /api/platform/sites/{slug}/files)
	ListFiles(w http.ResponseWriter, r *http.Request, slug Slug)
	// Delete a custom site file
	// (DELETE /api/platform/sites/{slug}/files/{path})
	DeleteFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath)
	// Download a custom site file
	// (GET /api/platform/sites/{slug}/files/{path})
	GetFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath)
	// Upload or replace a custom site file
	// (PUT /api/platform/sites/{slug}/files/{path})
	PutFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath)
	// Reset custom site to default
	// (POST /api/platform/sites/{slug}/reset)
	ResetSite(w http.ResponseWriter, r *http.Request, slug Slug)
	// Upload multiple files via multipart form
	// (POST /api/platform/sites/{slug}/upload)
	MultipartUpload(w http.ResponseWriter, r *http.Request, slug Slug)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListForums operation middleware
func (siw *ServerInterfaceWrapper) ListForums(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListForums(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProvisionForum operation middleware
func (siw *ServerInterfaceWrapper) ProvisionForum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProvisionForum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportForum operation middleware
func (siw *ServerInterfaceWrapper) ExportForum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportForum(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOwnedSites operation middleware
func (siw *ServerInterfaceWrapper) ListOwnedSites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwnedSites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFiles operation middleware
func (siw *ServerInterfaceWrapper) ListFiles(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiles(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFile operation middleware
func (siw *ServerInterfaceWrapper) DeleteFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path FilePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFile(w, r, slug, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFile operation middleware
func (siw *ServerInterfaceWrapper) GetFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path FilePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFile(w, r, slug, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFile operation middleware
func (siw *ServerInterfaceWrapper) PutFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path FilePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFile(w, r, slug, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSite operation middleware
func (siw *ServerInterfaceWrapper) ResetSite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSite(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MultipartUpload operation middleware
func (siw *ServerInterfaceWrapper) MultipartUpload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ForumlineIdentityScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MultipartUpload(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/platform/forums", wrapper.ListForums)
	m.HandleFunc("POST "+options.BaseURL+"/api/platform/forums", wrapper.ProvisionForum)
	m.HandleFunc("GET "+options.BaseURL+"/api/platform/forums/{slug}/export", wrapper.ExportForum)
	m.HandleFunc("GET "+options.BaseURL+"/api/platform/owned-sites", wrapper.ListOwnedSites)
	m.HandleFunc("GET "+options.BaseURL+"/api/platform/sites/{slug}/files", wrapper.ListFiles)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/platform/sites/{slug}/files/{path}", wrapper.DeleteFile)
	m.HandleFunc("GET "+options.BaseURL+"/api/platform/sites/{slug}/files/{path}", wrapper.GetFile)
	m.HandleFunc("PUT "+options.BaseURL+"/api/platform/sites/{slug}/files/{path}", wrapper.PutFile)
	m.HandleFunc("POST "+options.BaseURL+"/api/platform/sites/{slug}/reset", wrapper.ResetSite)
	m.HandleFunc("POST "+options.BaseURL+"/api/platform/sites/{slug}/upload", wrapper.MultipartUpload)

	return m
}

type ListForumsRequestObject struct {
}

type ListForumsResponseObject interface {
	VisitListForumsResponse(w http.ResponseWriter) error
}

type ListForums200JSONResponse []ForumSummary

func (response ListForums200JSONResponse) VisitListForumsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProvisionForumRequestObject struct {
	Body *ProvisionForumJSONRequestBody
}

type ProvisionForumResponseObject interface {
	VisitProvisionForumResponse(w http.ResponseWriter) error
}

type ProvisionForum201JSONResponse ProvisionResponse

func (response ProvisionForum201JSONResponse) VisitProvisionForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ProvisionForum400JSONResponse Error

func (response ProvisionForum400JSONResponse) VisitProvisionForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProvisionForum401JSONResponse Error

func (response ProvisionForum401JSONResponse) VisitProvisionForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ProvisionForum500JSONResponse Error

func (response ProvisionForum500JSONResponse) VisitProvisionForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportForumRequestObject struct {
	Slug Slug `json:"slug"`
}

type ExportForumResponseObject interface {
	VisitExportForumResponse(w http.ResponseWriter) error
}

type ExportForum200ResponseHeaders struct {
	ContentDisposition string
}

type ExportForum200JSONResponse struct {
	Body    ExportData
	Headers ExportForum200ResponseHeaders
}

func (response ExportForum200JSONResponse) VisitExportForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportForum401JSONResponse Error

func (response ExportForum401JSONResponse) VisitExportForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ExportForum403JSONResponse Error

func (response ExportForum403JSONResponse) VisitExportForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ExportForum404JSONResponse Error

func (response ExportForum404JSONResponse) VisitExportForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExportForum500JSONResponse Error

func (response ExportForum500JSONResponse) VisitExportForumResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnedSitesRequestObject struct {
}

type ListOwnedSitesResponseObject interface {
	VisitListOwnedSitesResponse(w http.ResponseWriter) error
}

type ListOwnedSites200JSONResponse []OwnedSite

func (response ListOwnedSites200JSONResponse) VisitListOwnedSitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOwnedSites401TextResponse string

func (response ListOwnedSites401TextResponse) VisitListOwnedSitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(401)

	_, err := w.Write([]byte(response))
	return err
}

type ListFilesRequestObject struct {
	Slug Slug `json:"slug"`
}

type ListFilesResponseObject interface {
	VisitListFilesResponse(w http.ResponseWriter) error
}

type ListFiles200JSONResponse FileManifestResponse

func (response ListFiles200JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles401JSONResponse Error

func (response ListFiles401JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles403JSONResponse Error

func (response ListFiles403JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles404JSONResponse Error

func (response ListFiles404JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles500JSONResponse Error

func (response ListFiles500JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFileRequestObject struct {
	Slug Slug     `json:"slug"`
	Path FilePath `json:"path"`
}

type DeleteFileResponseObject interface {
	VisitDeleteFileResponse(w http.ResponseWriter) error
}

type DeleteFile200JSONResponse DeleteFileResponse

func (response DeleteFile200JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile400JSONResponse Error

func (response DeleteFile400JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile401JSONResponse Error

func (response DeleteFile401JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile403JSONResponse Error

func (response DeleteFile403JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile404JSONResponse Error

func (response DeleteFile404JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile500JSONResponse Error

func (response DeleteFile500JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFileRequestObject struct {
	Slug Slug     `json:"slug"`
	Path FilePath `json:"path"`
}

type GetFileResponseObject interface {
	VisitGetFileResponse(w http.ResponseWriter) error
}

type GetFile200ResponseHeaders struct {
	ContentLength string
	ContentType   string
}

type GetFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       GetFile200ResponseHeaders
	ContentLength int64
}

func (response GetFile200ApplicationoctetStreamResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Length", fmt.Sprint(response.Headers.ContentLength))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetFile400JSONResponse Error

func (response GetFile400JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetFile401JSONResponse Error

func (response GetFile401JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetFile403JSONResponse Error

func (response GetFile403JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetFile404JSONResponse Error

func (response GetFile404JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetFile500JSONResponse Error

func (response GetFile500JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutFileRequestObject struct {
	Slug Slug     `json:"slug"`
	Path FilePath `json:"path"`
	Body io.Reader
}

type PutFileResponseObject interface {
	VisitPutFileResponse(w http.ResponseWriter) error
}

type PutFile200JSONResponse PutFileResponse

func (response PutFile200JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutFile400JSONResponse Error

func (response PutFile400JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutFile401JSONResponse Error

func (response PutFile401JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutFile403JSONResponse Error

func (response PutFile403JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutFile404JSONResponse Error

func (response PutFile404JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutFile413JSONResponse Error

func (response PutFile413JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type PutFile500JSONResponse Error

func (response PutFile500JSONResponse) VisitPutFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ResetSiteRequestObject struct {
	Slug Slug `json:"slug"`
}

type ResetSiteResponseObject interface {
	VisitResetSiteResponse(w http.ResponseWriter) error
}

type ResetSite200JSONResponse ResetResponse

func (response ResetSite200JSONResponse) VisitResetSiteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResetSite401JSONResponse Error

func (response ResetSite401JSONResponse) VisitResetSiteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResetSite403JSONResponse Error

func (response ResetSite403JSONResponse) VisitResetSiteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ResetSite404JSONResponse Error

func (response ResetSite404JSONResponse) VisitResetSiteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResetSite500JSONResponse Error

func (response ResetSite500JSONResponse) VisitResetSiteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUploadRequestObject struct {
	Slug Slug `json:"slug"`
	Body *multipart.Reader
}

type MultipartUploadResponseObject interface {
	VisitMultipartUploadResponse(w http.ResponseWriter) error
}

type MultipartUpload200JSONResponse MultipartUploadResponse

func (response MultipartUpload200JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUpload401JSONResponse Error

func (response MultipartUpload401JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUpload403JSONResponse Error

func (response MultipartUpload403JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUpload404JSONResponse Error

func (response MultipartUpload404JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUpload413JSONResponse Error

func (response MultipartUpload413JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type MultipartUpload500JSONResponse Error

func (response MultipartUpload500JSONResponse) VisitMultipartUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all active hosted forums
	// (GET /api/platform/forums)
	ListForums(ctx context.Context, request ListForumsRequestObject) (ListForumsResponseObject, error)
	// Provision a new hosted forum
	// (POST /api/platform/forums)
	ProvisionForum(ctx context.Context, request ProvisionForumRequestObject) (ProvisionForumResponseObject, error)
	// Export forum data as JSON
	// (GET /api/platform/forums/{slug}/export)
	ExportForum(ctx context.Context, request ExportForumRequestObject) (ExportForumResponseObject, error)
	// List forums owned by the caller
	// (GET /api/platform/owned-sites)
	ListOwnedSites(ctx context.Context, request ListOwnedSitesRequestObject) (ListOwnedSitesResponseObject, error)
	// List custom site files
	// (GET /api/platform/sites/{slug}/files)
	ListFiles(ctx context.Context, request ListFilesRequestObject) (ListFilesResponseObject, error)
	// Delete a custom site file
	// (DELETE /api/platform/sites/{slug}/files/{path})
	DeleteFile(ctx context.Context, request DeleteFileRequestObject) (DeleteFileResponseObject, error)
	// Download a custom site file
	// (GET /api/platform/sites/{slug}/files/{path})
	GetFile(ctx context.Context, request GetFileRequestObject) (GetFileResponseObject, error)
	// Upload or replace a custom site file
	// (PUT /api/platform/sites/{slug}/files/{path})
	PutFile(ctx context.Context, request PutFileRequestObject) (PutFileResponseObject, error)
	// Reset custom site to default
	// (POST /api/platform/sites/{slug}/reset)
	ResetSite(ctx context.Context, request ResetSiteRequestObject) (ResetSiteResponseObject, error)
	// Upload multiple files via multipart form
	// (POST /api/platform/sites/{slug}/upload)
	MultipartUpload(ctx context.Context, request MultipartUploadRequestObject) (MultipartUploadResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListForums operation middleware
func (sh *strictHandler) ListForums(w http.ResponseWriter, r *http.Request) {
	var request ListForumsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListForums(ctx, request.(ListForumsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListForums")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListForumsResponseObject); ok {
		if err := validResponse.VisitListForumsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProvisionForum operation middleware
func (sh *strictHandler) ProvisionForum(w http.ResponseWriter, r *http.Request) {
	var request ProvisionForumRequestObject

	var body ProvisionForumJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProvisionForum(ctx, request.(ProvisionForumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProvisionForum")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProvisionForumResponseObject); ok {
		if err := validResponse.VisitProvisionForumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportForum operation middleware
func (sh *strictHandler) ExportForum(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request ExportForumRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportForum(ctx, request.(ExportForumRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportForum")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportForumResponseObject); ok {
		if err := validResponse.VisitExportForumResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOwnedSites operation middleware
func (sh *strictHandler) ListOwnedSites(w http.ResponseWriter, r *http.Request) {
	var request ListOwnedSitesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwnedSites(ctx, request.(ListOwnedSitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwnedSites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnedSitesResponseObject); ok {
		if err := validResponse.VisitListOwnedSitesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFiles operation middleware
func (sh *strictHandler) ListFiles(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request ListFilesRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFiles(ctx, request.(ListFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFilesResponseObject); ok {
		if err := validResponse.VisitListFilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFile operation middleware
func (sh *strictHandler) DeleteFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath) {
	var request DeleteFileRequestObject

	request.Slug = slug
	request.Path = path

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFile(ctx, request.(DeleteFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFileResponseObject); ok {
		if err := validResponse.VisitDeleteFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFile operation middleware
func (sh *strictHandler) GetFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath) {
	var request GetFileRequestObject

	request.Slug = slug
	request.Path = path

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFile(ctx, request.(GetFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFileResponseObject); ok {
		if err := validResponse.VisitGetFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutFile operation middleware
func (sh *strictHandler) PutFile(w http.ResponseWriter, r *http.Request, slug Slug, path FilePath) {
	var request PutFileRequestObject

	request.Slug = slug
	request.Path = path

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutFile(ctx, request.(PutFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutFileResponseObject); ok {
		if err := validResponse.VisitPutFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResetSite operation middleware
func (sh *strictHandler) ResetSite(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request ResetSiteRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResetSite(ctx, request.(ResetSiteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetSite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResetSiteResponseObject); ok {
		if err := validResponse.VisitResetSiteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MultipartUpload operation middleware
func (sh *strictHandler) MultipartUpload(w http.ResponseWriter, r *http.Request, slug Slug) {
	var request MultipartUploadRequestObject

	request.Slug = slug

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MultipartUpload(ctx, request.(MultipartUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MultipartUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MultipartUploadResponseObject); ok {
		if err := validResponse.VisitMultipartUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce3PbOJL/Kl28rTq7iqKcx1zteWrrKs/b3MYzOTuzdXVRzoLJloQJCHAAUDYn5e9+",
	"1QBIkRIk2bGTndnxX5EJEN1oNH79ZD4nuSorJVFakxx/TiqmWYkWtftrxgW+Y3ZBvws0ueaV5Uomx8kp",
	"Cmb5EoGmQMXsAi65XXAJdoFguMUMflAgkBVczsEIZhYpSAXTLJuC1WyJ2jCRTqRUsOBFgdItZeDA4Lwk",
	"dsBYpi29TSvDNJseZnBSGwsLtkRgEpgQ6hILwCuL0nAls4lM0oQTg8RSkiaSlbj6S+MvNddYJMdW15gm",
	"Jl9gyWh3eMXKStBULgu8yha2FEma2KaiZ8ZqLufJ9XWaGFHPN8XxWum6BBqDA1NfFKpkXB5m8Gj09AiI",
	"SZ0zg8BEtWCyLlHzHPIF0ywnUYPSsGiqBUqTTmTOpFTW755GUBZeAixM2rpLx9vNdmnR2BkxnaS0iEVN",
	"y/3fBzb69Wj07x8Pwo/Rx89H6ZM/X7fPD//jTxGpXLc0nNK8RIEWX3OBp2gqJQ06xdKqQm05Gi89mlNs",
	"CpK0DdTMaVGY5PQiS9Ie97kxY2MbgVluTPSYVjL40BH72E1UFz9jbpPrNHmltdID0XxO0D9LWG0XKC3P",
	"GTEH3ZLX6dpusF1kuJe/1iWTI42sYBcCwc2CEo1hc7ef3Vz7RaM8X1VK25fMsk3BXij1qWT6k9lk53kY",
	"Aq0uDTAD/3X24w/glzXED7dYuvc2KIYHTGvW0N85szhXujvMPpkXfqy5DzILJiWK85miix6j5SeAn3A/",
	"FO15IBunZyEM3xe1oBDbqIXhe6CGTm2wOGd2k9ZP71+A5SUay8qKLuDlAj2W+9fgkhnINTKLBZGdKV3S",
	"OknBLI7ozU2FdrPqkoj9SeMsOU7+ZbyyNuMAGWOHnSdoWfeG4BLPyUA43tZZ9eoPngMI04b48CjGjFSW",
	"z8JlPq80zlCjzGOC/6E3E1Yz7+EM+jzsI3x3apUyNkLlnTL2PlbXylnsCAE/cg807ILgM0LivRu4BwpL",
	"xXM810qVESp/p0GgwTtTWkP3TT0fXtD27gywtifzlWjaY14Hr3V4GW417VmKdbXcBN4dlydmoMj2nzDJ",
	"Z2jsdh+gUx5WFJzWZeLdYMIu0Djj3sV4Ja125zg8uBPmQGzlnFrl/yjRsoJZlsHfsDHANIJuXVmaaEDw",
	"TziR05UbOCUnbDpwOabeBdvYuLFKszmeXzQ2di/eK8sEuEGoDRZw0TiIzWtjVem95j62cmn/7emKDpcW",
	"56j7hAQveQTNz/ww/FIry4BLT/OGa9cVYXpxAxtBvAtmLJThsMG/e1MDsX4ngma3DKzLc33bUdXrjEnE",
	"5+xt5vOmffBOe3TI+9eRgTYa2L2x4Je7VTo6Q5XdupezuiyZbvZuJxaP9J7BQckauEDAsrINeEYPs5id",
	"XMlhbc1aCPCDQ2vbxRJZh2qZRBtbm+dKntdaRJTr9C1dUlIptwrQ1Ftw3R5RVA7cVII1QHOGrL8npX0d",
	"kHbr6d4o1ouLJLasXeB2Xt0g8IICjxlHvT9QuIF29QTfko8p3EktLK+Ytj9VQrFiO3S72CRm+FGPHMwO",
	"Yh1DJxqie0s+7YxxgUUGr1i+CIcKC0aDOJHBr5vSfNrTMWhkRsmAuZ2MPyQGc402wys89uBOG4JJQk8m",
	"CVAQHTIEtNt1Q907jzWXoHa7jyHg69aehI1cokYwdZ6jMbNaiAbad7Mhq4OkwjB6vQVrawff8Zm2BxI7",
	"1B8vJRZkLiMQsv+mtzDv7/dAx8vmhpd+3zWKLrs/qm8V3S0f2/k7rZacfKtT/KVGY2+JoT9W3ikJeNQb",
	"HDL8DHJVlrXktnGKXnCT18aQUudKCbALLufmFqD1sgdXbsUtB3DS3Ba6zlq4WlsWnmOuSjQw/UwvXg/P",
	"dJrB2zaFNZGDHBaTRZe58smuVVYrhX4ma9ylsfpJrNix3zkdtR0e92jJ1mzVze+JxMs73ZUvM2M7NcF5",
	"zOfxhSkUnGs8+++34OdFlO5fDTiPeUDRjZxvvavf5tJ3Rq+/x+gZ13Z3PhIti3B78vI7WOAVFHxOfkI4",
	"4hZ2IVfSorTRm11Fs+ZnTHLLfw05zRCZOEPCDFxqbi3KW2U608TwX3GLoaKhzvmHA2aA9V2oXrrk8ZOn",
	"e0UfUs1OUoFsTNSnaHBH0Gcss3XEc3gmLlljYDpJNC1AkFoJtDhJpqBka2Md27IuiZ/hvB4v23DAU47x",
	"PAwmN3gO53zu39tQkjcnr7zn0ZrKjXS1xSs7JuP/vYNHg/YvtZ2N/hw7z9toolOiXVp4U+W498jQRYX+",
	"onxhMOhYT4ey77SvZWTzMGnTmNea2+aMQCGkGlrYfeP8attsQSaaQpG5Dg64beCnn968zOAMbRusryay",
	"qgI2s6ihXymQ84l0MEHLLDmD/+WWFSgyOA3bc/DKhICytu4FIG3zyReyqBOpLiXqkclVhQW4NE+v5rNA",
	"VqBeVX3+Z9SxNHrzciVYVvG/YePLM1zOVKvKLHeeUHi7e5fESoFZsrC2Msfj8dBWbaZYKFgYWZRMWqgE",
	"o3inhGfv3rjtVa1Vpe2Rl1AyyebO0VfGYtETo6NDG/wrk4Xw0UJdguAzzJtcIBz4vHMKghubhoT0oVu1",
	"lzkJ+R0igyVKO5EHXgFTKNSlDL9cKSjEIkrCC6HqYiaYRjh9fOiFLHiOAbuCjN5pVWmOluLwvVKy3IqB",
	"YOFdTzhJmnSJ7eRRdpQd0TuqQskqnhwnT7Kj7Il3ghZOdces4uNWvJ6aez5HG6vK2lpLA7hE3QDLXVor",
	"CDx4eu8X3ADKolJcWuAGqvpCBE8u3D/jirLD6pcXTaenb4rkOHnLjX3tGaK76yHfMff46KgHnC7HV1Ui",
	"LDX+2Xh3e1WX7AKgvXWCNh2yGRttKOgzGiAwCnIIejbAiOT4w8c0MW2OxW3JXc2I7Jz5ZXND6BS2/TEk",
	"2SO1G6eyZHHJI+wv09ZyCyxIIFjAhhOWgsY5N640zO1Eujc2safgGnOrdJOGG/YJaT7wssSCM4uiAa1q",
	"66qPzE7kFu8+crSdU9y6ldqHUM9V0dzqZHcd6EZ8dj00AlbXeL2hWY++Bv3grkS0yHusHZxhMYj3M1LE",
	"p7fU9l08+Xp0hI+/M8ELXxhywT6ZE7rsWKxKdS4nxQ1wuaTZpEYG9RKLlMI2siMNWPYJZQpK+9folbHz",
	"+QkDS+7iVtIIt69HX39fJ54kTIdmbArezDkBf/ctBPxGUtTJBDiR6ZDCKmqXneqbsw0EifoXHz5eD5Cl",
	"U7YIJMSA5TqNQv/YX+GxN4JbDYGvkRoHZRS8wUyrElgX0IVg72BVXEqhrS2lEEpL6US60lJKXmtX927/",
	"bJN7KSy7KplJoSsrpTCoKqUTmQ+q9WsTenVWcwguVnGlttZ2Z/CjFE2XIqxLcE4S5EwGjyCGY14Or7vM",
	"wqq56UNcTVZTxi7EpEO8k2nbqYurRo6tyONOL2wwSYPz5zh54VkYveSmUobHk1jPrGX5gvwhaBOqKWA2",
	"z2DKuqHvu7G/TNpQfBRo0o4myTRL+n1EGw1AvyW0eHr05Osz8oIJQWGCcWnmVdXCKWVg4+nXZ8PrCLEw",
	"U7Usvh1atk0YPpP/RYi46uNo1TyU128EhyToYkSO/3532DWT+TQdOUrOTKpZ8JJX59bVY3uuLxYukNvm",
	"/nbJ9W/jAq9y+bfxf/3enKiGBbXDLG7mXb6iEiHnGWsf3NYaF+0NvO0V/gJdcn67t5DDo8zdPe1pFEkP",
	"TrooMaZaTlKtoe26FPZqWBt/+kq4i/E7e9uLU1PgMhe1a4utQr1sItu+BDgw/FdM26yOSyyl8Oo9m6dt",
	"UsWlPnz4q5aoycSHujjUrrVwW6gWyuu/NSsY7RaJYd1Avi4mGu47ebBCfzAr1Pa51JItGRcu0FV6pSTk",
	"ODobVWu8A7CsZ5nMXfFk/LlidnG96oSOFAHdc3KDHa44/71fkunz1F4DggSPDx6RWjnEEGHVpf2FkJDu",
	"ndd9PfBV4SPSbr4NPEIj+LcL2t/4QBx8Vbj9XKGr/Twg1gNiiS8EJq/2wDbAaSc2pXE35mUIsl2FsMKc",
	"ovKb4042kX0/SLPLQWUKuvQlqyqXSWcWoY1e3zcVtloYgan/RPubxCiVW7QjYzWycqgWXa3rgktfMNjr",
	"Er9eq+NFgvy3KOexinK8lrc9Uk+TvuBvUc3cF/w/oOkfHU1Dj9/vG1UDEN4eV6t6RxVIadBYCZY7h450",
	"R4R4MXwwuRtd3xOq+hoJXKiioQOPIW0GJ+yKl3Xpn3pYMPDdyfNsIp+tfyxpjmHqG9xTmLqudvr35/Yf",
	"Jd2PSs79g2o+TSeSfqB/Mucz969Z+r8v8aJyP3iu/AM1m3U/Hrtf1s78KvbKugdXpYgXoOpvivs3KW7d",
	"K+Sfrh9dsr/ydX8Xab0faptN6lqd/jE1rwfA/x25z08ffYP9O620SoFgeo5wULIrgrdDUhEz+OgFr3LE",
	"Av/xyQh/h+6UKfft+D0rclvztDsl4TrpXNtbtJWhy0QIsZkJ8QHC6eMUNJZquZZ4SENbyRK1Nb4tyutr",
	"+NKjwBmrhYWzd8/AYknsoWu2MjBdMHPuyZ0Tuan7hIsJ14IsC5jSw/PBB0JuylHMmrimRJc3/+2lP4cN",
	"kzG9ImEPux0fkO8hcfClLu6p16TeRbaqvYh3ABEPc9tR5FmeY2XJ/Z2W7WdGY1pmVDDLpp1/65IFSvo8",
	"rtIBZsK3Qr5Wwg0sfTcMFunKR7HK4RCBAyvCg/Y/I1mlQsE70/66TaSvxRC6ac0aQ1Fv9Hue8NWPW1w2",
	"XeHGd4mYbCJbz/vR0clzsO5Dz3ZL5Id/D1wWfMmLmomAnDmrKiyA2eCgb6DW2udYd8Gubf5t5CiGurrl",
	"k921L2XWj4tEH7p/4XVoLfAf27rPXplZOXHDj6j3etKRT6LWO4Cvv6Unve2TucgNDlZco6mFNXBAb3Em",
	"Wn2DShnDLwQePqD7H86vDR2Q667tCkwO/5mKauEmePARLWYsOYMOj9x/77HbHN2csGvo85A5bN72TXhr",
	"X2XRK4Hs593NoFzOfVO6+0G2Ya1bq99jb1xaYk3tt7evw9budd/WaQ97BNalc/3x+v8DAAD//9vhUiXZ",
	"SwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
