when:
  - event: push
    branch: main
    path:
      include:
        - "services/website/**"
        - "deploy/docker/Dockerfile.website"
        - "deploy/compose/website/**"
  - event: manual

steps:
  - name: deploy
    image: bash
    commands:
      - ci/deploy.sh website
