when:
  - event: [push, pull_request, manual]

steps:
  - name: install
    image: bash
    commands:
      - pnpm install --frozen-lockfile

  - name: lint
    image: bash
    depends_on: [install]
    commands:
      - git init && git add .
      - npx lefthook run pre-commit --all-files --no-tty
