name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dagger/dagger-for-github@v7
        with:
          module: ci
          verb: call
          args: lint --source .
          version: "0.20.1"
